### ISSUE TITLE
expose information about storage devices

### ISSUE THREAD

**Issue by freeseacher** [fboender/ansible-cmdb#100]
Please add to fancy html template column about storage size.
For example something like 
/dev/sda 100G
/dev/sda1 60G
/dev/sdb 200G

**Comment by fboender** [comment]
I've added a new column with this information. While doing so, I also found a bug with disks of size 0, so I fixed that too ;-)

Thanks for the feature request. It will be included in the next release of Ansible-cmdb!

**Comment by freeseacher** [comment]
Thanks for that. but i talk not about disk size but about storage size. 
`ansible_devices.[i].size` var to be more specific. 

Let me explain what i want to get from that table. 

I got several vm-s from datacenter and want to check if they were provisioned well enough. 
to achieve that i have to check 4 components. 
* cpu count -- simply how many they are. 
* mem size -- simply size.
* storage size -- threre can be some variants. ssd, spinning disk, raw disks, and so on.
* interface count -- sometimes i need more interfaces than one. there will be perfect to see, just count. 

tnx.

**Comment by fboender** [comment]
Ah, I see!

I've reverted the change where I introduced the new column.

> cpu count -- simply how many they are.

This is present. Is it usable for you in the current way?

> mem size -- simply size.

Is also present.

> storage size -- threre can be some variants. ssd, spinning disk, raw disks, and so on.

I've added a column "PhysDisk size" that shows this. Can you see if it's the way you'd like it now?

> interface count -- sometimes i need more interfaces than one. there will be perfect to see, just count.

Also added a column for this.

Let me know what you think! You can find the new changes on the master branch.

Regards,

Ferry

**Comment by freeseacher** [comment]
seem something broken. 
![image](https://cloud.githubusercontent.com/assets/289277/22560828/65006b28-e98f-11e6-87ad-5bb8b7db2bcc.png)

all columns shown by default. they are not clickable

**Comment by fboender** [comment]
I had some strange problems too. I think its related to the column that I added and then removed. Can you try cleaning out your localStorage by typing this in the console (under the error message probably):

    window.localStorage.clear();

This fixed things for me.

**Comment by freeseacher** [comment]
ok. looks much better now.

**Comment by fboender** [comment]
I've added a "Clear settings" button to the template which users can click to reset the local storage.
