### ISSUE TITLE
show information about machine where data was generated

### ISSUE THREAD

**Issue by freeseacher** [fboender/ansible-cmdb#102]
Just some simple things, hostname, username. 
Probably report generated from `ansible-cmdb` will be sent by email or something. 
It will be perfect if there will be a posibility to find someone who generates that report

**Comment by fboender** [comment]
I've added the user and hostname on which the overview was generated at the top of the page. Can you take a look to see if this suits your needs?

**Comment by freeseacher** [comment]
looks good! tnx
