### ISSUE TITLE
please add some basic filter capabilities

### ISSUE THREAD

**Issue by freeseacher** [fboender/ansible-cmdb#104]
Probably adding some filters for table will do it much usable. 
just to illustrate: like this one http://js-grid.com/ 
let me explain what for.
for example i want to see only db group. or filter by virt type. or at least 4 cpu's and so on.

**Comment by fboender** [comment]
Hi Aleksey,

Thank you for the feature request. However, replacing the current DataTables with JSGrid would be a considerable amount of work. Basically 80% of the html_fancy template would have to be rewritten, retested, etc. So, regrettably, I'm currently going to have to decline implementing this feature requests. I am always open to Pull requests implementing this, naturally. 

Regards,

Ferry
