### ISSUE TITLE
Large host lists produce browser-killer pages

### ISSUE THREAD

**Issue by garbled1** [fboender/ansible-cmdb#110]
It would be nice if there were some way to make the pages generated split up a bit, maybe not have the full facts included, or linked as sub-pages.  When I generate a fancy_html list of my 850 some odd hosts, the resulting page is 33MB, and crashes any browser that encounters it due to ram consumption.

I'm currently splitting it up by sub-domain, but one of them is still 350+ hosts and browsers get all icky when they hit it.

**Comment by fboender** [comment]
Hi!

I'm curious, can you tell me if the Host overview table is usable and responsive with that amount of hosts?

I'm going to have to think about this one a bit. Ansible-cmdb is currently oriented towards output of a single file, due to how the templating works. But obviously that's going to be problematic with 850+ hosts. I'll have to do some experimentation.

I'll get back to you on this one soon!

**Comment by garbled1** [comment]
The hosts overview table is pretty responsive.  Well, to be fair, no browser survives loading the full 850, but in the group of 250 or so, it's nice and snappy.

To be honest, I don't even use the fact data at the bottom much.  What I really want is that overview area.  Maybe if the fact data was a sub-page?  I'm mostly interested in quick data, like ram, cpus, etc.  Things I can grab without digging around vsphere or something.  For example, a group asked me for a report on how much ram/cpu their hosts had, so all I had to do was search, pick the columns, and cut & paste.

**Comment by fboender** [comment]
There are other templates available such as the CSV template. It generates a Comma Seperated File you can load into Excel or something. It only has the information from the host overview table at the top.

I'll add a parameter to the fancy_html template to turn off the extended host information after the overview table. That at least should be enough so that you can get all hosts in a single file. i've also got some ideas for generating separate files, but it takes a little more programming.

**Comment by garbled1** [comment]
Yeah, I knew about the csv, but the host overview page is so pretty and functional, it's exactly what I want. :)

**Comment by fboender** [comment]
Hey!

I've pushed a change to the master branch that implements a new parameter for the `html_fancy` template: `host_details=0|1`. Surprisingly enough, it lets you turn off the host details ;-) Example usage:

    ansible-cmdb -p host_details=0 -i hosts out > cmdb.html

Putting host details in separate files is the next thing I'm going to tackle. It requires a bit of rewriting of the current code, so it may take a little longer.

Best regards, and thanks for the bug report!

**Comment by garbled1** [comment]
Awesome, thank you!

**Comment by fboender** [comment]
I still have to implement split pages so I'm reopening this ;-)

**Comment by fboender** [comment]
I still have to implement split pages so I'm reopening this ;-)

**Comment by infrascripting** [comment]
FWIW my solution (running on a Apache) was to write a python script (with beautifulsoup4) that parsed out the host details and put them in separate files (header and footer included), and then changed the link in the hosts summary from `#hostname` to `hostname.html`.

```
/var/www/html/
|- index.html
|- host1.html
|- host2.html
```

**Comment by fboender** [comment]
I'm very close to an implementation of a fancy_html_split template. It's taking a while because I'm also completely changing the fancy_html template itself so I can reuse it's code. This will also aid other people in creating their own templates.

**Comment by fboender** [comment]
Hey!

I just commited a set of changes to the master branch that implement a split version of the html_fancy template. It generates a `cmdb/` directory with an `index.html` file and a separate file for each host's details.

Usage:

    ansible-cmdb -t html_fancy_split -i hosts out 

Which generates the `cmdb/` directory in the current working dir.

Can you give it a whirl, see if it works for you?

**Comment by infrascripting** [comment]
I installed it in a virtualenv using python3 to test it. Two things (the second of which may be a result of working around the first)

1. 
```
Traceback (most recent call last):
  File "/Users/cziryaka/.virtualenvs/python3/bin/ansible-cmdb", line 4, in <module>
    __import__('pkg_resources').run_script('ansible-cmdb===MASTER', 'ansible-cmdb')
  File "/Users/cziryaka/.virtualenvs/python3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/cziryaka/.virtualenvs/python3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1499, in run_script
    exec(code, namespace, namespace)
  File "/Users/cziryaka/.virtualenvs/python3/lib/python3.6/site-packages/ansible_cmdb-MASTER-py3.6.egg/EGG-INFO/scripts/ansible-cmdb", line 21, in <module>
    import ansiblecmdb.render as render
  File "/Users/cziryaka/.virtualenvs/python3/lib/python3.6/site-packages/ansible_cmdb-MASTER-py3.6.egg/ansiblecmdb/render.py", line 3, in <module>
    import util
ModuleNotFoundError: No module named 'util'
```

2. After commenting out the import util
```
Parsing fact dir: ../inventories/three
Reading host facts from ../inventories/three/discfuiap01dxm1.dev.oclc.org
Reading host facts from ../inventories/three/esbeadap02mxm1.nit.oclc.org
Reading host facts from ../inventories/three/identdlws02mxm1.nit.oclc.org
Parsing host vars (dir): ../inventories/three.inv
Rendering host overview for discfuiap01dxm1.dev.oclc.org
Rendering host overview for esbeadap02mxm1.nit.oclc.org
Rendering host overview for identdlws02mxm1.nit.oclc.org
Whoops, it looks like something went wrong while rendering the template.

The reported error was: TypeError: write() argument must be str, not bytes

The full error was:

    Traceback (most recent call last):
      File "/Users/cziryaka/.virtualenvs/python3/lib/python3.6/site-packages/ansible_cmdb-MASTER-py3.6.egg/EGG-INFO/scripts/ansible-cmdb", line 157, in <module>
        output = renderer.render(ansible.hosts, params)
      File "/Users/cziryaka/.virtualenvs/python3/lib/python3.6/site-packages/ansible_cmdb-MASTER-py3.6.egg/ansiblecmdb/render.py", line 48, in render
        return self._render_py(hosts, vars)
      File "/Users/cziryaka/.virtualenvs/python3/lib/python3.6/site-packages/ansible_cmdb-MASTER-py3.6.egg/ansiblecmdb/render.py", line 67, in _render_py
        return module.render(hosts, vars=vars, tpl_dirs=self.tpl_dirs)
      File "/Users/cziryaka/.virtualenvs/python3/lib/python3.6/site-packages/ansible_cmdb-MASTER-py3.6.egg/ansiblecmdb/data/tpl/html_fancy_split.py", line 21, in render
        f.write(template.render(hosts=hosts, **vars).lstrip())
    TypeError: write() argument must be str, not bytes

The output is probably not correct.
```

**Comment by fboender** [comment]
Hi,

thanks for testing so quickly!

The util import was pointless, so I removed it. I then got the same error as you. Turns out I forgot to update the tests for generate the html_fancy_split template with Python3 and it barfed on the utf8 output. I've pushed a set of fixes that should address these problems.

It seems to be working properly for me now with Python v2 and 3. Could you try the latest master?

**Comment by infrascripting** [comment]
Everything seems to be working fine. Nice job!

**Comment by fboender** [comment]
Thanks for the feature request and the help in testing it. Sorry it took so long! Sometimes work and social life get in the way ;-)

**Comment by infrascripting** [comment]
Lol, this _is_ work for me ;P
