### ISSUE TITLE
Hyperlink to CPU info

### ISSUE THREAD

**Issue by jensenbox** [fboender/ansible-cmdb#111]
Would be awesome to hyperlink out to something like CPUBenchmark.

For example:

http://www.cpubenchmark.net/cpu.php?cpu=AMD+Athlon+64+X2+Dual+Core+4200%2B

**Comment by fboender** [comment]
Hi Christian!

Good idea, I'll add this soon!

Regards,

**Comment by fboender** [comment]
The latest version in master now contains a link to the cpubenchmark site. I've also added the CPU type to the host details (it was only present in the host overview table previously).

Thanks for the feature request!
