### ISSUE TITLE
Support multiple hosts files.

### ISSUE THREAD

**Issue by peterny** [fboender/ansible-cmdb#112]
Thanks for a really useful application!
Only issue so far is that the Groups column (after enabling it in the Host Overview) shows no data.
I don't see how it could work, however, since "ansible -m setup ..." does not produce any group data (in my case at least, ansible version 2.2.1.0, on RedHat).
Have I misunderstood something?

**Comment by scathatheworm** [comment]
If you feed it the inventory with -i, it will pick up group information from your ansible inventory and match it to the collected facts.

**Comment by fboender** [comment]
Hi Peterny,

Like David said (thanks for the reply David!), you need to include your 'hosts' file with `-i`. For example, if your hosts file looks like:

    [cust.megacorp]
    db1.dev.megacorp.com   dtap=dev  comment="Old database server"

and you run Ansible-cmdb with:

    ansible-cmdb -i ./hosts out/ > overview.html

It will then contain the groups data. In this case, host "db1.dev.megacorp.com" would have a group "cust.megacorp". You can also add comments and such to the `hosts` file, which will end up in the other columns.

Hope this helps and if you still have questions, don't hesitate to ask. I'm going to close this report for now, in the understanding that it'll work now for you.

Thanks for your report!

**Comment by peterny** [comment]
Thanks, I should have read the "Full usage" guide, explaining the ansible-cmdb -i option.

However, in my case we have several inventory files (currently four), so I just ran "ansible -m setup ..." on each, with the same output dir, then ran ansible-cmdb on that dir.

The guide says -i takes a single parameter, so I guess it is not possible to specify four inventory files?
(Perhaps the solution could be to use an inventory *dir*, which we are currently not using, so that would require a change in our ansible setup).

/ Peter

**Comment by fboender** [comment]
>  so that would require a change in our ansible setup).

Ansible-cmdb should adapt to your setup, not the other way around ;-)

I'll look into supporting multiple hosts files. It should be too difficult.

**Comment by fboender** [comment]
For now, It should be possible to to write a small wrapper script that concatenates your different hosts files and then calls ansible-cmdb on the result. Something like:

    cat hosts* > combined_hosts
    ansible-cmdb -i combined_hosts out > cmdb.html

Regards,

Ferry

**Comment by peterny** [comment]
Super, I will use the combined hosts workaround for now.

**Comment by fboender** [comment]
Ansible-cmdb now supports multiple `-i` parameters. For example:

    ansible-cmdb example/out -i example/hosts -i example/hosts2 > cmdb.html

The enhancement is currently in master and will be included in the next release.

Thanks for the feature request!

**Comment by fboender** [comment]
Turns out the way I implemented this doesn't work properly in Python v2. I'll have to change it.

**Comment by fboender** [comment]
Fixed. You can specify multiple inventories by comma-separating them on the `-i` switch:

    ansible-cmdb -i hosts,hosts2 out > cmdb.html
