### ISSUE TITLE
Odd lines in generated html

### ISSUE THREAD

**Issue by NikitaGl** [fboender/ansible-cmdb#114]
Like i understood, it grabs host names from my inventory "hosts" file and marks them red and "no information collected". 
Is it possible to restrict app to collect host names from inventory and use only collected host information?

**Comment by fboender** [comment]
Hi!

If you don't specify a hosts file (no -i option) it should only list hosts for which actual information was retrieved. You may have to delete any empty files from the facts directory.

I'll implement a feature to filter out empty hosts in the near future.

**Comment by NikitaGl** [comment]
Yup, just as you said, I don't specify hosts file, but still, it gathers them to final html form, doesn't matter if I use custom or default template.
Exact command I'm using to generate form:
[root@ansible ansible]# ansible-cmdb -t /home/nikita/html_fancy_custom.tpl -f /etc/ansible/ansible-cmdb-facts/ -p host_details=1 > ./ansible-cmdb-html/index.html

**Comment by fboender** [comment]
Ah it is likely autodetecting them or something. I'm on vacation at the moment so it's hard for me to to replicate the behaviour as all I have with me is my phone. I'm afraid you'll have to wait until next Monday before I'll have a chance to look at it. :-( Apologies! I'll look into it as soon as I'm back!

**Comment by NikitaGl** [comment]
Sure, no problem at all, have a good vacation C:
Meanwhile, I'll try to prevent empty lines to appear on a template level.

**Comment by fboender** [comment]
Hi!

I've added a "-p skip_empty=1" param to the html_fancy template in the master branch. If you specify it, hosts for which no data has been collected will be skipped in the output. The new param will be included in the next release.

Thanks for the feature request and let me know if this solves your problems!

Regards.
