### ISSUE TITLE
Issue with group vars

### ISSUE THREAD

**Issue by damarsan** [fboender/ansible-cmdb#120]
Hello, thanks for this great tool, I've found that ansible group vars: [http://docs.ansible.com/ansible/intro_inventory.html#group-variables](url) are parsed as a host, so html generated is wrong, maybe this can be skipped.

**Comment by fboender** [comment]
Hi!

Thanks for the bug report. Do you have an example of group vars that are improperly parsed by Ansible-cmdb? The following seems to work properly for me:

    [prod]
    eek.electricmonk.nl
    zoltar.electricmonk.nl comment="Trés Load balancer"
    
    [prod:vars]
    dtap=prod

This properly applies the "dtap=prod" variable to the hosts `eek.electricmonk.nl` and `zoltar.electricmonk.nl`.

**Comment by damarsan** [comment]
OK, it fails with this example:

[machines]
machine1 ansible_host=129.21.12.13 dtap=proxy comment=eu-west-1
machine2 ansible_host=129.21.12.143 dtap=twitter comment=eu-west-1
machine3 ansible_host=129.21.12.141 dtap=twitter comment=eu-west-1

[machines:vars]
ansible_user=ec2-user
Phoenix.X-11_2 ansible_host=52.49.213.169 dtap=proxy comment=eu-west-1

**Comment by wampyl** [comment]
hello. Thans for the tool.I have the same question.
exapmle:
[test]
172.30.30.11 ansible_ssh_user=root ansible_ssh_pass=admin123 datp=dev comment="dev01"

**Comment by fboender** [comment]
Hey all,

I'm afraid I'm not sure what the problem is. The examples you posted seem to be behaving the way I expect them to. Can you elaborate a bit on what you're expecting to see, what the actual output is and why that output is incorrect?

Thanks!

**Comment by damarsan** [comment]
Could you try with my example(using 4 vars)?, my problem is that "ec2-user" var appears as a host. May be could be ansible bug?

**Comment by fboender** [comment]
I've tried with the following scenario:

The `hosts` file looks like this:

    fboender @ jib ~/Projects/fboender/ansible-cmdb (master) $ cat hosts 
    [machines]
    machine1 ansible_host=129.21.12.13 dtap=proxy comment=eu-west-1 
    machine2 ansible_host=129.21.12.143 dtap=twitter comment=eu-west-1
    machine3 ansible_host=129.21.12.141 dtap=twitter comment=eu-west-1
    
    [machines:vars]
    ansible_user=ec2-user

The `out/` directory looks like this:

    fboender @ jib ~/Projects/fboender/ansible-cmdb (master) $ ls out/
    machine1  machine2  machine3

I generate the CMDB with the following command:

    ansible-cmdb -i hosts out/ > cmdb.html

For me, this results in an overview with three hosts: machine1, machine2 and machine3. Each host has a "Custom variable": `ansible_user=ec2-user`.

Screenshots:

* [Overview](https://electricmonk.nl/temp/out_overview.png)
* [Details](https://electricmonk.nl/temp/out_details.png)

Everything seems in order. Could it be that you have a lingering "ec2-user" file in your facts dir, or some misconfiguration in your hosts file somewhere? You could try reducing the hosts file and files in the fact dir until the problem goes away or you're left with a minimal example of the bug still happening.

If you want, you can send the hosts file and facts dir to my email address (ferry.boender@gmail.com) and I can have a look at it. All information you send me is treated confidential and will be securely deleted once the issue has been resolved.

Regards,

Ferry

**Comment by wampyl** [comment]
I do again and successful.
I tried `ansible-cmdb -i hosts out/ > cmdb.html` instead of `ansible-cmdb out/ > overview.html`,and then successful.
Thanks.

**Comment by damarsan** [comment]
Yes, I've tested again and worked fine, maybe it was an issue with my inventory.

Apologies and many thanks.

**Comment by fboender** [comment]
That's great to hear! I'm glad it's working for you now. If you run into any other problems or have questions don't hesitate to ask!

Regards 

Ferry
