### ISSUE TITLE
Host_Vars

### ISSUE THREAD

**Issue by rlb2015** [fboender/ansible-cmdb#122]
I think I saw that this was a known issue someplace, but just in case, I figured I'd let you know...
 
I know that you have to have host_vars files in the format of  variable="value" rather than variable: "value" or variable: value.   However, even when no errors generated, it does not appear to populate the variables to the host information in the output (rather it interprets them as hosts so I get variables listed as hosts.

This is using one of the documented inventory folder structures I have not attempted to try a different structure to see if that makes a difference.

inventory/
+Production/
++hosts
++host_vars/
++group_vars/
+Development/
++hosts
++host_vars/
++group_vars/

**Comment by fboender** [comment]
Hey bob!

How are you invoking ansible-cmdb? And do you have a sample of a file in one of the host_vars dirs (filename and a piece of contents) that isn't being loaded properly?

**Comment by rlb2015** [comment]
I believe I may have mis-interpreted how the folder structure worked, I had thought that specifying the inventory/ as the inventory in the ansible.cfg file, ansible would pick up the host_vars and group_vars because they were on the same level as the hosts file automatically.   However, I found that ansible doesn't even see them unless I add ansible -i inventory/Production to the command regardless of the inventory setting in the ansible.cfg file.   

I tested this time by:

ansible -i ./inventory/prod/ -m setup --tree ../out all
ansible-cmdb  ../out/ > prod.html

Which fixed the vars being interpreted as hosts, however ansible is not parsing the variables, so it's not ansible-cmdb, sorry for the false alarm.

**Comment by fboender** [comment]
No problem!

If you want ansible-cmdb to pick up the variables, you'll also have to specify the hosts location:

    ansible-cmdb .-i inventory/prod ./out/ > prod.html

Good luck and if you have any other questions, please don't hesitate to ask!
