### ISSUE TITLE
how do you include custom facts in templates?

### ISSUE THREAD

**Issue by lanmand** [fboender/ansible-cmdb#124]
how do you include custom facts in templates?
I have created a custom fact on some of my servers (ansible_local.latestospatch.latestospatch)
how can i include this value in templates and html reports?

**Comment by fboender** [comment]
Hi!

You can either place the facts on the machine you're controlling with ansible in the `/etc/ansible/facts.d/` directory. For example:

    fboender @ client $ cat /etc/ansible/facts.d/users.fact
    {
      "users": ["root", "fboender"]
    }

The custom facts will be retrieved by ansible automatically and when you generate the overview, the variables will be placed under the 'Host local facts' section.

You can also create your own hand-crafted ansible facts output directory and put custom and local facts in there. This is done on the ansible control server. For example:

    fboender @ ansible $ cat out_custom/host.example.com
    {
        "custom_facts": {
            "software": {
                "apache": {
                  "version": "2.4",
                  "install_src": "backport_deb"
                }
            }
        },
        "ansible_facts": {
            "ansible_local": {
                "foo": "bar"
            }
        }
    }

This can be combined with the host facts that ansible fetched itself with the "`setup`" module. This requires that you specify two output directories:

    ansible-cmdb -i hosts out/ out_custom/ > cmdb.html

This will place custom_facts under the heading "Custom variables" and the local facts under "Host local facts".

**Comment by lanmand** [comment]
Thanks for a quick reply.
I already have the custom fact in place and collected in my out/ directory.
It already apears in the "Host local facts"

Now i want to be able to report on the fact using either
ansible-cmdb -t txt_table --columns name,os,ip,mem,my-custom-fact out/
or
ansible-cmdb -t html_fancy out/ > overview.html
(and get the "my-custom-fact" column as a filter in the top of the html-page)

So i think i need to edit the templates txt_table.tpl and html_fancy.tpl
to get the custom_fact as a column in the txt and column/filter in the html
how do i do that ?

**Comment by fboender** [comment]
Yes, you'll have to modify the templates for that. For the `html_fancy` template, the easiest way is to edit the `html_fancy_defs.html` file. You'll need to add a "row" to the column definition list in the `var_cols()` method. Then you should add a custom "Column functions" (search for that exact text in the file) method. That should be enough. The procedure is largely the same with the `txt_table.html` template, except that you only have to add a row to the `cols` dict.

If you edit the existing files, they'll be overwritten when you upgrade ansible-cmdb. So you may want to make a copy:

* Copy `html_fancy_defs.html` to `my_html_fancy_defs.html`
* Copy `html_fancy.tpl` to `my_html_fancy.tpl`.
* Modify `html_fancy.tpl` and replace any occurance of 'html_fancy' with 'my_html_fancy'.

You can then use `--template my_html_fancy` to render your custom template.

Hope that helps! If you need any more help, please let me know!

**Comment by jroman111** [comment]
Can you include similar instruction
For the html_fancy_split. I am looking to add my custom facts to the details section like installed software / versions that Get populated on the control machine using set_fact while running my playbooks/tasks? Can you add something so that these facts will be automatically pickup/displayed if you use some kind of “custom” fact_name suffix or prefix?
