### ISSUE TITLE
Provide way to collect only certain facts

### ISSUE THREAD

**Issue by smalleni** [fboender/ansible-cmdb#126]
Memory, SWAP etc keep changing over time, and might be outdated if linked from an inventory wiki in a large lab etc. It would be great if we can provide user a way to collect only hardware related facts(which do not change that frequently)

**Comment by fboender** [comment]
Hello!

It's nearly impossible to determine which facts change often and which don't. Memory usage is a simple one, as it changes nearly constantly. But what about IPs / adapters? Every time a docker container or OpenVPN is started, the interfaces change. So it's a very grayish area and I don't see a One Size Fits Alll solution for this.

The easiest thing to do would be to create your own template with just the facts you want. See https://github.com/fboender/ansible-cmdb#templates for some help on how to specify your own template. Basically, you'll want to make a copy of html_fancy.tpl and html_fancy_defs.tpl and modify html_fancy_defs.tpl to suit your needs.

Regards,

Ferry
