### ISSUE TITLE
Support comments in host file

### ISSUE THREAD

**Issue by nymous** [fboender/ansible-cmdb#128]
In our inventory file, we have comments at the end of a line, to remind us what each machine is doing.
It is causing ansible_cmdb to ignore the whole line (and the variables defined on it).
It correctly ignores a commented line (beginning with a `#`) though.

Example:
`inventory/hosts`
```ini
[group]
server1 ansible_host=192.186.1.100 ansible_port=9999 #comment
```
Command:
`ansible-cmdb -i inventory/ out/ > overview.html`

Output:
`Unsupported vars syntax. Skipping line: server1 ansible_host=192.186.1.100 ansible_port=9999 #comment`

**Comment by nymous** [comment]
Reading through the code, I can see that this line https://github.com/fboender/ansible-cmdb/blob/master/src/ansiblecmdb/parser.py#L209 should make it work. Weird...

**Comment by dglinder** [comment]
@nymous It appears that the ``token`` in the case of the example above might be ``#comment`` not strictly ``#``. I'm just learning Python, but instead of this line:

                if token == '#':

..would this work?

                if token,startswith('#'):

**Comment by nymous** [comment]
Did some more tests, it seems like it.
If the line is `server1 ansible_host=192.168.1.100 # comment` it works, because the token parsed is `#`, but if the comment is `#comment`, then the token is `#comment`.

Your fix does work \o/

**Comment by fboender** [comment]
Pull request merged. Thanks!
