### ISSUE TITLE
Support nested inventories folders

### ISSUE THREAD

**Issue by nymous** [fboender/ansible-cmdb#132]
It looks like ansible_cmdb tries to parse every file recursively in the given inventory folder as a host file.
E.g, with the following structure
```
inventories/
  - hosts
  - group_vars/
    - all.yml
    - webservers.yml
  - company_name_dev/
    - hosts
    - group_vars/
      - all.yml
      - database.yml
```

`group_vars/all.yml`:
```
tags:
  - test
  - dev
```
and the command `ansible-cmdb -d -i ~/inventories/ ~/out/ > overview.html`, the `hosts` files are parsed correctly (they give the correct groups to hosts), but `group_vars/all.yml` is parsed as a host file as well.
It creates a host named `tags`, and then fails to parse the following lines (`Unsupported vars syntax. Skipping line: - test`).

After the host parsing step, the `group_vars` folders are searched, but only at the root level. `company_name_dev/group_vars/all.yml` isn't read.

Would it be possible to skip parsing `group_vars` (and `host_vars` probably?) as hosts files, and look for `group_vars` folders anywhere in the inventory tree?

**Comment by fboender** [comment]
> It looks like ansible_cmdb tries to parse every file recursively in the given inventory folder as a host file.

Are you sure? `group_vars` should be handled differently.

I'm not familiar with the following construction:

```
inventories/
  - company_name_dev/
```

I can't find anything about how ansible would handle such a construction. Do you happen to have a link to the documentation where this setup is described?

> group_vars/all.yml is parsed as a host file as well.

This issue has been fixed in a recent commit.

On a general note, I should probably say that I fear that variable parsing in ansible-cmdb will never be fully reliable. There are tons and tons of undocumented features and edge cases in Ansible itself and in the libraries it uses. The host / group vars inclusion in ansible-cmdb should be seen more as a bit of an extra rather than an authoritive source on which variables a given host has.

**Comment by fboender** [comment]
FYI, it's possible to specify multiple inventories with the `-i` switch. For example:

```
ansible-cmdb -i inventories/global/hosts,inventories/company_dev/hosts ./out > cmdb.html
```

That won't work with your current setup though.

**Comment by nymous** [comment]
I did some tests with ansible, and it does **not** support `group_vars` folders under the root level (and it has just bitten me on a deployment...) So that's a non-issue 😅

Though, if I understand this logic correctly https://github.com/fboender/ansible-cmdb/blob/master/src/ansiblecmdb/ansible.py#L82, the `_handle_inventory` method goes through everything in the given inventory path, and if it is a directory it will enter it and treat it recursively. So it doesn't handle the root `group_vars` differently and parses the files in it as hosts files (and it seems confirmed by my tests).

Also, thanks for the info on passing multiple inventories, it could come in handy!

**Comment by fboender** [comment]
> the _handle_inventory method goes through everything in the given inventory path, and if it is a directory it will enter it and treat it recursively.

Yes, that's correct. Apparently that's a thing Ansible supports, where you can have a `hosts` file but also various dynamic inventory scripts and such in the same dir. Someone once filed a feature request to scan a given directory for inventory files / scripts. 

If I recall correctly, we fixed the issue of group_vars and host_vars being tried for inventory files already in a recent pull request by you (commit c5124abcbca)? Does this fix your issue mentioned in this ticket?

**Comment by nymous** [comment]
Yes, this issue is now fixed!

Do you know when you will package a new release?

**Comment by fboender** [comment]
I've released new packages for .deb, .rpm and source. I still have to upload a new python package. I'll do that in about 15 hours from now.

**Comment by fboender** [comment]
Thanks for the feedback and issue reporting! I've closed this issue. If there is anything else, don't hesitate to open a new one or reopen this one if it turns out it's not right after all!
