### ISSUE TITLE
large inventory (1000+ hosts) is still slow even with _split

### ISSUE THREAD

**Issue by Hr0bar** [fboender/ansible-cmdb#135]
I thought that using --columns  would hide the rest of columns by not including them at all, but its just a default filter and they are still in the file.

Would it be possible to add something like --exclude, which would NOT include those columns at all?  The idea is that optionally removing stuff that we are not interested in like disk usage, disk sizes etc would GREATLY reduce the index.html size.

just FYI with around 900 hosts the index.html while using _split is 6.4M, which still takes a lot of time to load/process. By excluding some stuff we could probably get that down to less than 1M

Thanks for consideration, this functionality would be greatly appreciated.

**Comment by fboender** [comment]
Hi Hr0bar!

Thanks for the bug report!

> I thought that using --columns would hide the rest of columns by not including them at all, but its just a default filter and they are still in the file.

It does for the 'static' templates such as CSV. It doesn't for the interactive HTML ones. A bit of an oversight on my part, which I can't correct anymore without breaking backwards compatibility. :slightly_frowning_face: 

I've implemented a `--exclude-cols` option and pushed it to master. It works the same as the `--columns` option. Can you see if this works for you?

**Comment by Hr0bar** [comment]
Thanks a lot!  I will try it tomorrow and let you know.

**Comment by Hr0bar** [comment]
Getting it like this now, nothing shows up (it shows up while the page loads, but once completely loaded all rows get hidden)

https://imgur.com/a/C2YGv

was generated with:

`ansible-cmdb -t html_fancy_split --exclude-cols mem_usage,swap_usage,disk_usage,physdisk_size out/`

Note that I merely overwritten the affected files from the commit instead of doing make install, but I guess that should be enough, let me know in case is isnt.

One additional observation regarding big filesizes:

`
</td>
                  <td>
    SLES 11.1
</td>
                  <td>
  2.6.32.54-0.3-default
</td>
                  <td>
  x86_64 / x86_64
</td>
                  <td>
  VMware / guest
</td>
                  <td>
`

There is a lot of probably non-needed newlines and empty space characters, removing those could potentially save some bandwidth as well (in case it wouldnt affect anything)

**Comment by fboender** [comment]
can you try clearing the settings using the button on the top-right corner? I've had some problems with that.

**Comment by Hr0bar** [comment]
oh, that helped!  Works now. Again, thanks for this new functionality. 

 Regarding that empty chars/newlines I guess thats from the external js library for the table, so probably not much to be done there. I tested removing the empty characters and not needed newlines and it basically halved the filesize from 800kB the to ~450kB.

So thanks, removing mem_usage,swap_usage,disk_usage,physdisk_size reduced it down to 800kB which is great.

**Comment by fboender** [comment]
> Regarding that empty chars/newlines I guess thats from the external js library for the table, so probably not much to be done there

No, I think it's from the templating system used. I can get rid of it probably. I don't have the time right now, but I can do it in a few hours.  I don't want to sacrifice too much of the template readability for space, but a 50% reduction in size should help.

**Comment by fboender** [comment]
I managed to get rid of a few spaces without impacting readability, but not everything. I think this will have to do. Spaces shouldn't have much effect on rendering time.

I'm gonna close this ticket. If there's anything missing, please let me know!
