### ISSUE TITLE
Determining type of inventory_path {}".format(inventory_path)

### ISSUE THREAD

**Issue by emanuelefilippello** [fboender/ansible-cmdb#139]
Configuration:

> ansible 2.4.1.0
>   config file = /etc/ansible/ansible.cfg
>   configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
>   ansible python module location = /usr/lib/python2.6/site-packages/ansible
>   executable location = /usr/bin/ansible
>   python version = 2.6.6 (r266:84292, Aug  9 2016, 06:11:56) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]

When run ansible-cmdb print this error:

> Traceback (most recent call last):
>   File "/usr/bin/ansible-cmdb", line 153, in <module>
>     ansible = ansiblecmdb.Ansible(args, hosts_files, options.fact_cache, debug=options.debug)
>   File "/usr/lib/ansible-cmdb/ansiblecmdb/ansible.py", line 61, in __init__
>     self._handle_inventory(inventory_path)
>   File "/usr/lib/ansible-cmdb/ansiblecmdb/ansible.py", line 82, in _handle_inventory
>     self.log.debug("Determining type of inventory_path {}".format(inventory_path))
> ValueError: zero length field name in format

The output file it will not be created.

**Comment by emanuelefilippello** [comment]
Add, the error appear only when I declare a inventory option (-i)

**Comment by jmclavier** [comment]
like the post above,
whatever the argument used with the option inventory (-i) (hosts, inventory directory),
ansible-cmdb exit with ValueError: zero length field name in format
many tests done with basic hosts files
That's a shame, this tool is interesting!

**Comment by fboender** [comment]
Are you using Python v2.6? Official Python v2.6 support ended in October 2013. Given that ansible-cmdb would require a lot of work (not to mention ugly hacks ;-) ) to support v2.6, I'm afraid I can't offer support for it. Please upgrade to Python 2.7 or higher.

I'm going to close this issue, as I'm fairly certain this is the problem. If not, please reopen this issue.

I'll also add a notice to the README mentioning the minimum requirements for ansible-cmdb.

**Comment by emanuelefilippello** [comment]
I run with a machine with Python 2.7.5, another error:

Error while parsing hosts contents: 'Traceback (most recent call last):
  File "/usr/lib/ansible-cmdb/ansiblecmdb/parser.py", line 31, in __init__
    self.sections = self._parse_hosts_contents(hosts_contents)
  File "/usr/lib/ansible-cmdb/ansiblecmdb/parser.py", line 96, in _parse_hosts_contents
    name, vars = self._parse_line_entry(line, cur_section['type'])
  File "/usr/lib/ansible-cmdb/ansiblecmdb/parser.py", line 160, in _parse_line_entry
    key_values = self._parse_line_vars(line)
  File "/usr/lib/ansible-cmdb/ansiblecmdb/parser.py", line 194, in _parse_line_vars
    key_values = self._parse_vars(tokens)
  File "/usr/lib/ansible-cmdb/ansiblecmdb/parser.py", line 214, in _parse_vars
    k, v = token.split('=', 1)
ValueError: need more than 1 value to unpack
'. Invalid hosts file?
