### ISSUE TITLE
Feature Request: Make host-information collapsable

### ISSUE THREAD

**Issue by rndmh3ro** [fboender/ansible-cmdb#14]
When you have hundreds of hosts in your inventory, the resulting overview gets really large.
There should be a possibility to collapse the host-information at the heading and maybe at the sub-headings, too.
There should be a setting to make the information auto-collapsed by default, maybe stored in a cookie or via cli-settings.

**Comment by fboender** [comment]
Hey Sebastion. I'm currently working on a feature that will implement this. In combination with the new `-p` flag I've added that lets you pass parameters to templates, you'll be able to auto-collapse all the host information by default.

I'm not sure if I'm going to implement persistence of opened items. That is, if you reload the overview page, whether the items you previously opened are automatically opened again. I'm slightly pressed for time at the moment, so I might have to implement that at a later time.

**Comment by alexbarton** [comment]
We have lots of hosts, too … so +1 :smile:

**Comment by wmangano** [comment]
+1

>500 hosts

**Comment by freeseacher** [comment]
i have much fewer hosts (~30) but i think that should be done

**Comment by fboender** [comment]
In the spirit of "better late than never", I've pushed a new branch called "collapse" to the repository. It contains an initial version of collapsable host detail information. I'd love to hear some feedback on it!

**Comment by freeseacher** [comment]
ok. looks much better for me. maybe we it will be better with collapse button somewhere near open all.

**Comment by fboender** [comment]
Yes, I'm planning on implementing that, but I couldn't get it to work right away and I wanted some feedback on the work so far. I'll look into implementing that tomorrow.

**Comment by fboender** [comment]
"Open all" will now change to "Close all" when all items are opened. I've also made minor other improvements. I'm going to close this feature request. This functionality will be included in the next release, which should (hopefully) happen tomorrow. 

Thank you all for you suggestions and feedback!
