### ISSUE TITLE
Is it possible to change the SQL template to include new fields?

### ISSUE THREAD

**Issue by neemiasjr** [fboender/ansible-cmdb#141]
I would like to include new fields in SQL and insert all the IP, netmask and interfaces of each host. It is possible. Is it only necessary to change the ansible-cmdb/src/ansiblecmdb/data/tpl/sql.tpl file and include the new fields?

**Comment by fboender** [comment]
Hi!

Yes, all you have to do is make a copy of the sql.tpl file and include the new fields. You should add them to both the table definition (CREATE TABLE) and the INSERT query. You can then pass your custom sql.tpl file as a parameter using `--template` / `-t`.

Regards,

Ferry
