### ISSUE TITLE
groups不显示

### ISSUE THREAD

**Issue by wuhongtao2016** [fboender/ansible-cmdb#142]
![image](https://user-images.githubusercontent.com/18021028/34923044-fbcc53ba-f9d2-11e7-8fa4-f8efaf7bfb42.png)

**Comment by wuhongtao2016** [comment]
![image](https://user-images.githubusercontent.com/18021028/34923066-2a0e944a-f9d3-11e7-829a-8e38a24977a7.png)

**Comment by fboender** [comment]
Hi!

Did you specify the `-i` parameter and point it to your hosts / inventory file? Like this:

    $ ansible-cmdb -i ./hosts out/ > overview.html

Regards,

**Comment by egormin** [comment]
Hello, I faced the same issue. Groups and DTAP fields are empty. I read the comment (I mean -i switch using) and tried to use it, however, I've got an error:

![image](https://user-images.githubusercontent.com/17744515/35440043-c3c5780e-02ae-11e8-991e-95ba66a36993.png)

**Comment by fboender** [comment]
Are you using Python v2.6?

**Comment by egormin** [comment]
I'm using Python 2.6.6

**Comment by fboender** [comment]
Hi egormin,

I'm afraid Python 2.6 is not supported. Official support from the Python Foundation for Python 2.6.6 ended in October 2013. You should probably upgrade, as it also no longer receives security fixes.

I'm going to close this issue, as wuhongtao2016 isn't responding. If you're still experiencing issues after upgrading to a newer version of Python, please don't hesitate to open a new issue!

Regards
