### ISSUE TITLE
ansible-cmdb not loading the custom/local facts into sqllite file

### ISSUE THREAD

**Issue by rakesh561** [fboender/ansible-cmdb#145]
ansible-cmdb not loading the custom/local facts into sqllite file:-

I have converted two of the facts files into sqllite to load into mysql but seems like its not converting custom/local facts that it generated 

DROP TABLE IF EXISTS hosts;
CREATE TABLE hosts (
    name VARCHAR(255),
    fqdn VARCHAR(255),
    main_ip VARCHAR(15),
    os_name VARCHAR(80),
    os_version VARCHAR(40),
    system VARCHAR(40),
    kernel VARCHAR(40),
    arch_hardware VARCHAR(12),
    arch_userspace VARCHAR(12),
    virt_type VARCHAR(20),
    virt_role VARCHAR(20),
    cpu_type VARCHAR(60),
    vcpus INT,
    ram FLOAT,
    disk_total FLOAT,
    disk_free FLOAT
);

    INSERT INTO hosts (
        name,
        fqdn,
        main_ip,
        os_name,
        os_version,
        system,
        kernel,
        arch_hardware,
        arch_userspace,
        virt_type,
        virt_role,
        cpu_type,
        vcpus,
        ram,
        disk_total,
        disk_free
    ) VALUES (
        "nxgkpi-wc-a2p.sys.comcast.net",
        "nxgkpi-wc-a2p.sys.comcast.net",
        "",
        "RedHat",
        "7.2",
        "Linux",
        "3.10.0-327.36.3.el7.x86_64",
        "x86_64",
        "x86_64",
        "?",
        "?",
        "",
        0,
        0.0,
        0,
        0
    );
    INSERT INTO hosts (
        name,
        fqdn,
        main_ip,
        os_name,
        os_version,
        system,
        kernel,
        arch_hardware,
        arch_userspace,
        virt_type,
        virt_role,
        cpu_type,
        vcpus,
        ram,
        disk_total,
        disk_free
    ) VALUES (
        "nxgkpi-wc-a1p.sys.comcast.net",
        "nxgkpi-wc-a1p.sys.comcast.net",
        "",
        "CentOS",
        "7.2.1511",
        "Linux",
        "3.10.0-327.36.3.el7.x86_64",
        "x86_64",
        "x86_64",
        "?",
        "?",
        "",
        0,
        0.0,
        0,
        0
    );

Below is the file that contains all the facts but if you look at above sql file i dont see those i22 checks facts

**Comment by fboender** [comment]
The SQL template currently only loads basic host info, much like the CSV and text templates. Loading custom / local facts into it would be near impossible, as they are different every time. I think you should consider the SQL template as more of an example template than something truly useful and supported unfortunately.

Regards.

Ferry
