### ISSUE TITLE
Help Sorting factor_facts

### ISSUE THREAD

**Issue by jroman111** [fboender/ansible-cmdb#150]
Is possible you can incorporate or assist with syntax for adding a sort for facter_facts in html_fancy_defs.html. 

Regards,
Jim

**Comment by fboender** [comment]
Hi Jim,

Sorry for the late reply. I'm going to have to come back to you on this one. I think I may have a fix in place. I just need to test it before pushing it to the master branch.

**Comment by fboender** [comment]
Hey Jim!

I've pushed commit ad4ecf8 to the master branch. Can you check to see if this is what you want?

**Comment by jroman111** [comment]
Changes work perfect and are exactly what I was looking for. Thank you so much for incorporating the sort which is so useful in ordering/grouping my custom facts 

Regards
Jim
