### ISSUE TITLE
custom_facts from facts.d folder on hosts

### ISSUE THREAD

**Issue by lsalsich** [fboender/ansible-cmdb#152]
First: This app is a huge help. Thanks. 

My question: I'm trying to work with custom_facts as referenced here https://github.com/fboender/ansible-cmdb#custom-facts, but I'm not sure I'm trying to work with it in the way it was designed. 

I can place JSON into an 'out_custom' folder for processing as described, but this seems of limited value since the point of Ansible setup is to get updated facts for each host without having to hardcode JSON. 

Is there a way for cmdb to process the custom facts feature which is built into ansible?  Dynamically generated by ansible using the /etc/ansible/facts.d folder on hosts? 

I would like to use the facts.d functionality to obtain custom facts from scripts on the hosts which output JSON dynamically - not from static JSON. 

In the CMDB documentation, it stated that custom_facts must be in the 'custom_facts' key. OK. Is there a way to modify that so the cmdb custom_facts processes the native custom facts from Ansible facts.d format? 

The JSON output from '/etc/ansible/facts.d/custom_facts.fact' on host1 in my example is like this: 

`         "ansible_local": {
            "custom_facts": {
                "services": {
                    "apache": {
                        "install_src": "backport_deb", 
                        "version": "2.4"
                    }, 
                    "mysql-server": {
                        "install_src": "manual_compile", 
                        "version": "5.5"
                    }, 
                    "redis": {
                        "install_src": "manual_compile", 
                        "version": "3.0.7"
                    }
                }
            }
        }`

,where I want to process the facts under 'services'. But, Ansible adds the 'ansible_local' key. 

This is not an 'issue' - just a question / request on how I might be able to use ansible custom_facts in a dynamic way with CMDB.

Thanks!

**Comment by fboender** [comment]
Hi lsalsich!

Ansible-cmdb should already do what you want it to do in basically the exact way you're trying to do it. The facts from a hosts's `/etc/ansible/facts.d/` should appear under a heading "Host local facts". I do exactly the same thing. Can you verify that when you execute:

    ansible -m setup --tree out/ all

The output for one of the hosts in `out/` actually contains a structure similar to this (some stuff stripped for brevity sake):

    {
       "changed" : false,
       "failed" : false,
       "ansible_facts" : {
          "ansible_local" : {
             "firewall_status" : {
                "policy_drop_v6" : false,
                "ufw_enabled" : true,
                "firewall_detection" : true,
                "policy_drop_v4" : false,
                "ferm_enabled" : false
             },
             "services" : {
                "services" : [
                   {
                      "users" : [],
                      "protocol" : "tcp",
                      "port" : "*:43302"
                   },
                ]
             }
          }
       }
    }

The fact that you have them in `"ansible_local": { "custom_facts": { "services":` shouldn't matter at all. The method of showing that information is to just recursively dump everything under "ansible_local" to the output file. So it should already include your info.

**Comment by fboender** [comment]
Pushed commit 5a5a2eff4f to clarify the different between Custom Variables and Host Local Facts.

**Comment by fboender** [comment]
Glad to be of help, and glad this wasn't a bug, because for the life of me I couldn't figure out why that would happen! ;-) Like I said in another comment, I've tried to clear up the description in the README a bit. I hope it's clearer now for users.

Thanks for the report and making ansible-cmdb a better tool!
