### ISSUE TITLE
ansible awx

### ISSUE THREAD

**Issue by ghost** [fboender/ansible-cmdb#157]
has anyone attempted to get the facts out of awx and into ansible-cmdb?

**Comment by fboender** [comment]
Not that I know off. I'm not familiar with how AWX gathers and makes available facts, but generally ansible-cmdb should be able to deal with facts in yaml, json and ini-style format from dynamic scripts and fact directories.

**Comment by twotwenty** [comment]
I'll see what I can dig up with my AWX instance 
in case you ever want to try awx geerlinguy has a nice easy to use docker-compose yaml 

```
https://github.com/geerlingguy/awx-container/blob/master/docker-compose.yml
```

once you run it can take a large amount of time for the database to deploy itself

**Comment by fboender** [comment]
As I won't have the time to work in this myself, and there hasn't been any activity here in a while, I'm going to close this issue. Don't hesitate to re-open it if you still think it's worthwhile!

**Comment by mitchnielsen** [comment]
We're definitely interested in this topic in our group. We're currently building workarounds to get facts from Ansible separately from AWX so we can generate CMDB reports, but it would be fantastic if we could do this directly from AWX.

**Comment by Usama-A** [comment]
As per `https://adam.younglogic.com/2018/08/ansible-tower-inventory-cli/` we can export json using something like `curl -s -k -u $CREDS http://awx.example.com/api/v2/hosts/\[1-500\]/ansible_facts/ | jq > cmdb.json` very much a hack job not sure how to import single file into ansible-cmdb

**Comment by Usama-A** [comment]
for posterity.
create folder /var/lib/awx/projects/CMDB on awx host machine. Give it 777 permissions run playbook below `ansible-cmdb -t txt_table --columns name,os,ip,mem,cpus,virt /var/lib/awx/projects/CMDB/`

`---
- 
 name: gather_facts
 hosts: all
 gather_facts: 'true'
 tasks:
    - name: Gather facts
      setup:
      register: ansible_facts_setup
   
    - local_action: copy content={{ ansible_facts_setup }} dest=/var/lib/awx/projects/CMDB/{{ inventory_hostname }}`
