### ISSUE TITLE
the disk_free in sql template incorrect

### ISSUE THREAD

**Issue by benamazing** [fboender/ansible-cmdb#159]
i just used the sql template, and found the disk_free field in the sql template is incorrect. 

# The code in the sql.tpl

`<%def name="col_disk_free(host)"><%
  for i in jsonxs(host, 'ansible_facts.ansible_mounts', default=[]):
    if i["mount"] == '/':
      try:
        disk_free = i["size_total"] - i["size_available"]
        return round(disk_free / 1073741824.0, 1)
      except:
        return 0
      endtry
    endif
  endfor
  return 0
%></%def>`

Actually the i['size_available'] is already the disk free size, i['size_total'] - i['size_available'] is actually the disk used size.

**Comment by fboender** [comment]
Fixed in master. Thanks for the bug report!
