### ISSUE TITLE
network nodes

### ISSUE THREAD

**Issue by Ondjultomte** [fboender/ansible-cmdb#163]
Would it be possible to gather facts about ie cisco switches ? serial, ios version , modules , etc. ?

**Comment by fboender** [comment]
Hi Ondjultomte!

Gathering the facts is up to Ansible itself. Ansible-cmdb merely reuses those facts. Have a look at the Ansible [ios module](https://docs.ansible.com/ansible/devel/modules/ios_facts_module.html), which seems to do what you'd like.

I *think* the facts should be automatically included in Ansible-cmdb if they are gathered by ansible. If not, please re-open this issue, and I'll have a look at it. If you can, please include an example gathered fact file (from the `out/` directory as generated by the `ansible -m setup --tree out/ all` command).
