### ISSUE TITLE
Cant clone

### ISSUE THREAD

**Issue by Noname2244** [fboender/ansible-cmdb#164]
"sudo git clone git@github.com:fboender/ansible-cmdb.git
Klonar till "ansible-cmdb"...
ssh: connect to host github.com port 22: Connection refused
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists."

any one else having problems?

**Comment by chicks-net** [comment]
https://status.github.com/messages says everything is up and I haven't had any problems today.
