### ISSUE TITLE
Error when using JSON template

### ISSUE THREAD

**Issue by greg75** [fboender/ansible-cmdb#165]
The syntax used in `ansiblecmdb/data
/tpl/json.tpl` will error out with the output below when using Python3. Modifying the print statement to use parens addresses the issue.
```
The reported error was: SyntaxException: (SyntaxError) invalid syntax (<unknown>, line 9) ('import json\n\nclass CustEncoder(js
on.JSONEncoder):\n') in file '/home/user/.local/share/virtualenvs/ansible-venv/lib/python3.5/site-packages/ansiblecmdb/data
/tpl/json.tpl' at line: 1 char: 1
```

**Comment by fboender** [comment]
Thanks for the bug report! I've fixed this in the latest master branch.

**Comment by greg75** [comment]
Awesome tool btw. I set out to do write my own bridge between my 
inventory and an sql backend I needed for a specific application, and 
then thought to myself <someone must have done this already>. Great job, 
and it's really nice to see it's still maintained.

Cheers,

Greg

------ Original Message ------

**Comment by fboender** [comment]
Thanks! Glad it's of help!
