### ISSUE TITLE
TypeError: unsupported operand type(s) for /

### ISSUE THREAD

**Issue by coryrwagner** [fboender/ansible-cmdb#17]
I'm getting this error with the latest code from the repo. This is the first time I've tried generating a report for this data and, from the error, I can't tell what's causing this issue. I'm getting a similar error with yesterday's code, which also says "Error parsing: hosts: No JSON object could be decoded" before the traceback.
```
Traceback (most recent call last):
  File "/usr/local/bin/ansible-cmdb", line 310, in <module>
    sys.stdout.write(mytemplate.render(hosts=ansible.hosts, **params))
  File "/usr/lib64/python2.6/site-packages/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/lib64/python2.6/site-packages/mako/runtime.py", line 803, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/lib64/python2.6/site-packages/mako/runtime.py", line 835, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib64/python2.6/site-packages/mako/runtime.py", line 860, in _exec_template
    callable_(context, *args, **kwargs)
  File "_usr_local_lib_ansible_cmdb_html_fancy_tpl", line 139, in render_body
  File "_usr_local_lib_ansible_cmdb_html_fancy_tpl", line 39, in col_mem
  File "_usr_local_lib_ansible_cmdb_html_fancy_tpl", line 313, in render_col_mem
TypeError: unsupported operand type(s) for /: 'unicode' and 'float'
```

**Comment by fboender** [comment]
Hey Cory!

Thanks for the bug report Looks like something's going wrong in the rendering of the memory. 

Can you run the following command in the `out/` directory and paste the results?:

    grep "ansible_memtotal_mb" *
    
The output should look something like this:

    app.uat.local:        "ansible_memtotal_mb": 1496, 
    centos.dev.local:        "ansible_memtotal_mb": 996, 
    db01.prod.local:        "ansible_memtotal_mb": 496, 

Thanks!

**Comment by coryrwagner** [comment]
I don't see anything strange, other than some have values that are quoted (Solaris) and some do not (Linux), like this:
```
        "ansible_memtotal_mb": 129161,
        "ansible_memtotal_mb": "131072",
        "ansible_memtotal_mb": "131072",
        "ansible_memtotal_mb": "13824",
        "ansible_memtotal_mb": 15947,
        "ansible_memtotal_mb": 15947,
        "ansible_memtotal_mb": 15951,
        "ansible_memtotal_mb": "16160",
```

**Comment by fboender** [comment]
Ah, that explains it. The quoted values are interpreted as strings by default, but ansible-cmdb expects them to be integers. I've commited a fix for memtotal_mb, but there might be more items in the Solaris files that are wrong. Can you try against the master branch to see if it works for you now? If there a more similar errors, it might be helpful if you supplied me with a Solaris output.

**Comment by coryrwagner** [comment]
That fixed the problem with the memory column.
