### ISSUE TITLE
Output has to be tuned

### ISSUE THREAD

**Issue by ramkumarcrk** [fboender/ansible-cmdb#170]
Hello,
Thanks for the good work to make this rpm available. 
would like to get nice format for the below entry  from the html_fancy output.
Current Output:
SELinux? | {u'status': u'enabled', u'policyvers': 24, u'type': u'targeted', u'mode': u'permissive', u'config_mode': u'permissive'}
-- | --
Expected as :
 SELinux status:                 enabled
SELinuxfs mount:                /selinux
Current mode:                   enforcing
Mode from config file:          enforcing
Policy version:                 24
Policy from config file:        targeted

How to achieve this !  Thanks in advance.

**Comment by fboender** [comment]
Hi Ramkumar!

This has been fixed in the "master" branch of Ansible-cmdb. See also #175
