### ISSUE TITLE
HTML output for Windows target

### ISSUE THREAD

**Issue by michaeljconklin** [fboender/ansible-cmdb#173]
I am able to use the default html_fancy template for the host files gathered from Linux machines (looks amazing, by the way!).  But I have configured Ansible on a Windows workstation to gather data there, and the report generation fails.  I am pulling the data with winrm using Kerberos authentication.

Output from the ansible-cmdb command against the windows data file:

ansible-cmdb -t html_fancy -d windows 
config_dir = /etc/ansible/
data_dir = /usr/local/lib/python3.5/dist-packages/ansiblecmdb/data
tpl_dir = /usr/local/lib/python3.5/dist-packages/ansiblecmdb/data/tpl
static_dir = /usr/local/lib/python3.5/dist-packages/ansiblecmdb/data/static
inventory files = None
template params = {'data_dir': '/usr/local/lib/python3.5/dist-packages/ansiblecmdb/data', 'log': <logging.RootLogger object at 0x7f407ac2fdd8>, 'exclude_columns': None, 'version': '1.27', 'columns': None, 'lib_dir': '/usr/local/lib/python3.5/dist-packages/ansiblecmdb/data'}
Parsing fact dir: windows
Reading host facts from windows/tab.urmc-sh.rochester.edu
Rendering host overview for tab.urmc-sh.rochester.edu
Rendering host details for tab.urmc-sh.rochester.edu
Whoops, it looks like something went wrong while rendering the template.

The reported error was: TypeError: unorderable types: dict() < dict()

The full error was:
    
    Traceback (most recent call last):
      File "/usr/local/bin/../lib/ansiblecmdb/ansible-cmdb.py", line 177, in <module>
        output = renderer.render(ansible.hosts, params)
      File "/usr/local/lib/python3.5/dist-packages/ansiblecmdb/render.py", line 42, in render
        return self._render_mako(hosts, vars)
      File "/usr/local/lib/python3.5/dist-packages/ansiblecmdb/render.py", line 59, in _render_mako
        return template.render(hosts=hosts, **vars)
      File "/usr/local/lib/python3.5/dist-packages/mako/template.py", line 462, in render
        return runtime._render(self, self.callable_, args, data)
      File "/usr/local/lib/python3.5/dist-packages/mako/runtime.py", line 838, in _render
        **_kwargs_for_callable(callable_, data))
      File "/usr/local/lib/python3.5/dist-packages/mako/runtime.py", line 873, in _render_context
        _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
      File "/usr/local/lib/python3.5/dist-packages/mako/runtime.py", line 899, in _exec_template
        callable_(context, *args, **kwargs)
      File "/usr/local/lib/python3.5/dist-packages/ansiblecmdb/data/tpl/html_fancy.tpl", line 34, in render_body
        <% html_host_details(hosts, collapsed=collapsed, skip_empty=skip_empty) %>
      File "/usr/local/lib/python3.5/dist-packages/ansiblecmdb/data/tpl/html_fancy_defs.html", line 297, in render_html_host_details
        <% html_host_detail(host, collapsed=collapsed, skip_empty=skip_empty) %>
      File "/usr/local/lib/python3.5/dist-packages/ansiblecmdb/data/tpl/html_fancy_defs.html", line 291, in html_host_detail
        <%def name="html_host_details(hosts, collapsed=False, skip_empty=False)">
      File "/usr/local/lib/python3.5/dist-packages/ansiblecmdb/data/tpl/html_fancy_defs.html", line 331, in render_html_host_detail
        <% host_network(host, collapsed_class) %>
      File "/usr/local/lib/python3.5/dist-packages/ansiblecmdb/data/tpl/html_fancy_defs.html", line 302, in host_network
        <%def name="html_host_detail(host, collapsed=False, skip_empty=False)">
      File "/usr/local/lib/python3.5/dist-packages/ansiblecmdb/data/tpl/html_fancy_defs.html", line 858, in render_host_network
        % for iface in sorted(jsonxs(host, 'ansible_facts.ansible_interfaces', default=[])):
    TypeError: unorderable types: dict() < dict()
    
The output is probably not correct.

The Windows data file:

{"ansible_facts": {"ansible_architecture": "64-bit", "ansible_bios_date": "11/07/2012", "ansible_bios_version": "A07", "ansible_date_time": {"date": "2018-08-03", "day": "03", "epoch": "1533282910.67037", "hour": "07", "iso8601": "2018-08-03T11:55:10Z", "iso8601_basic": "20180803T075510670369", "iso8601_basic_short": "20180803T075510", "iso8601_micro": "2018-08-03T11:55:10.670369Z", "minute": "55", "month": "08", "second": "10", "time": "07:55:10", "tz": "Eastern Standard Time", "tz_offset": "-04:00", "weekday": "Friday", "weekday_number": "5", "weeknumber": "30", "year": "2018"}, "ansible_distribution": "Microsoft Windows 10 Enterprise", "ansible_distribution_major_version": "10", "ansible_distribution_version": "10.0.15063.0", "ansible_domain": "urmc-sh.rochester.edu", "ansible_env": {"ALLUSERSPROFILE": "C:\\ProgramData", "APPDATA": "C:\\Users\\mconklin\\AppData\\Roaming", "COMPUTERNAME": "TAB", "ComSpec": "C:\\WINDOWS\\system32\\cmd.exe", "CommonProgramFiles": "C:\\Program Files\\Common Files", "CommonProgramFiles(x86)": "C:\\Program Files (x86)\\Common Files", "CommonProgramW6432": "C:\\Program Files\\Common Files", "HOMEDRIVE": "H:", "HOMEPATH": "", "HOMESHARE": "\\\\NTHdrive03\\mconklin", "LOCALAPPDATA": "C:\\Users\\mconklin\\AppData\\Local", "LOGONSERVER": "\\\\URMCDC02", "NUMBER_OF_PROCESSORS": "8", "OS": "Windows_NT", "OneDrive": "C:\\Users\\mconklin\\OneDrive", "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL", "PROCESSOR_ARCHITECTURE": "AMD64", "PROCESSOR_IDENTIFIER": "Intel64 Family 6 Model 45 Stepping 7, GenuineIntel", "PROCESSOR_LEVEL": "6", "PROCESSOR_REVISION": "2d07", "PROMPT": "$P$G", "PSExecutionPolicyPreference": "Unrestricted", "PSModulePath": "C:\\Users\\mconklin\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules", "PUBLIC": "C:\\Users\\Public", "Path": "C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Business Objects\\Common\\3.5\\bin\\NOTES\\;C:\\Program Files (x86)\\Business Objects\\Common\\3.5\\bin\\NOTES\\DATA\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\HEAT\\;%USERPROFILE%\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Users\\mconklin\\AppData\\Local\\hyper\\app-2.0.0\\resources\\bin;C:\\Users\\mconklin\\.dotnet\\tools", "ProgramData": "C:\\ProgramData", "ProgramFiles": "C:\\Program Files", "ProgramFiles(x86)": "C:\\Program Files (x86)", "ProgramW6432": "C:\\Program Files", "SystemDrive": "C:", "SystemRoot": "C:\\WINDOWS", "TEMP": "C:\\Users\\mconklin\\AppData\\Local\\Temp", "TMP": "C:\\Users\\mconklin\\AppData\\Local\\Temp", "UATDATA": "C:\\WINDOWS\\CCM\\UATData\\D9F8C395-CAB8-491d-B8AC-179A1FE1BE77", "USERDNSDOMAIN": "URMC-SH.ROCHESTER.EDU", "USERDOMAIN": "URMC-SH", "USERDOMAIN_ROAMINGPROFILE": "URMC-SH", "USERNAME": "mconklin", "USERPROFILE": "C:\\Users\\mconklin", "VBOX_MSI_INSTALL_PATH": "C:\\Program Files\\Oracle\\VirtualBox", "windir": "C:\\WINDOWS"}, "ansible_fqdn": "TAB.urmc-sh.rochester.edu", "ansible_hostname": "TAB", "ansible_interfaces": [{"connection_name": "Ethernet", "default_gateway": "172.19.227.250", "dns_domain": "urmc-sh.rochester.edu", "interface_index": 4, "interface_name": "Intel(R) 82579LM Gigabit Network Connection", "macaddress": "90:B1:1C:87:7D:23"}, {"connection_name": "VirtualBox Host-Only Network", "default_gateway": null, "dns_domain": null, "interface_index": 3, "interface_name": "VirtualBox Host-Only Ethernet Adapter", "macaddress": "0A:00:27:00:00:03"}], "ansible_ip_addresses": ["172.19.224.97", "fe80::a59d:4ee:441d:5dcb", "192.168.56.1", "fe80::6525:fc3e:f8d7:d8e7"], "ansible_kernel": "10.0.15063.0", "ansible_lastboot": "2018-07-26 09:12:14Z", "ansible_machine_id": "S-1-5-21-2696100945-1221859291-1499886027", "ansible_memtotal_mb": 8150, "ansible_nodename": "TAB.urmc-sh.rochester.edu", "ansible_os_family": "Windows", "ansible_os_name": "Microsoft Windows 10 Enterprise", "ansible_owner_contact": "", "ansible_owner_name": "super", "ansible_powershell_version": 5, "ansible_processor": ["GenuineIntel", "Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz", "GenuineIntel", "Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz", "GenuineIntel", "Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz", "GenuineIntel", "Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz", "GenuineIntel", "Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz", "GenuineIntel", "Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz", "GenuineIntel", "Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz", "GenuineIntel", "Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz"], "ansible_processor_cores": 4, "ansible_processor_count": 1, "ansible_processor_threads_per_core": 2, "ansible_processor_vcpus": 8, "ansible_product_name": "Precision T3600", "ansible_product_serial": "9RPJRW1", "ansible_reboot_pending": true, "ansible_swaptotal_mb": 0, "ansible_system": "Win32NT", "ansible_system_description": "", "ansible_system_vendor": "Dell Inc.", "ansible_uptime_seconds": 686578, "ansible_user_dir": "C:\\Users\\mconklin", "ansible_user_gecos": "", "ansible_user_id": "mconklin", "ansible_user_sid": "S-1-5-21-329068152-583907252-725345543-139127", "ansible_win_rm_certificate_expires": "2021-07-31 10:26:35", "ansible_windows_domain": "urmc-sh.rochester.edu", "ansible_windows_domain_member": true, "ansible_windows_domain_role": "Member workstation", "gather_subset": ["all"], "module_setup": true}, "changed": false}

**Comment by michaeljconklin** [comment]
Just an update:

I have been able to get the default HTML template to work with other Windows workstations.  There is something specific about the JSON above that breaks when being parsed by the ansible-cmdb code.

**Comment by fboender** [comment]
Hi Michael,

Thanks for the bug report!

I'm surprised it can even load that output you've pasted, as it doesn't seem valid json. I'm getting the following error:

    json: Invalid \escape: line 1 column 821 (char 820)
    
Probably due to "P" being 'escaped' by that backslash in the windows path:

    {"ALLUSERSPROFILE": "C:\ProgramData",

Anyway, that part seems to working for you, so I'll focus on the actual issue you're having.

The problem happens when Ansible tries to sort the list of interface names:

    % for iface in sorted(jsonxs(host, 'ansible_facts.ansible_interfaces', default=[])):

In all Ansible fact output files I've seen so far, the interfaces part looks like this:

    "ansible_interfaces": [
        "lo", 
        "eth0"
    ], 
    
So it tries to sort "lo" and "eth0", which is fine, because python can actually sort strings.

However, in that windows file, it looks like this:

    [
        {
            "connection_name": "Ethernet",
            ...
            "macaddress": "90:B1:1C:87:7D:23"
        },
        {
            "connection_name": "VirtualBox Host-Only Network",
            ...
            "macaddress": "0A:00:27:00:00:03"
        }
    ]

And it tries to sort two dictionaries, but that's not something Python can actually do out-of-the-box.

The only solution I can think of is to check whether the list of interfaces contains strings or something else, and to only sort it if it contains strings.

I'll try to whip up a fix tomorrow if I have the time.

**Comment by fboender** [comment]
I've pushed some new commits to Master that should fix these problems. Can you have a look to see if it works for you now?

**Comment by michaeljconklin** [comment]
Works great!  I tested it against the one Windows system that previously didn't work at all, as well as the other systems that were ok before.  The new version is able to parse all of the json files properly.  Thanks very much.  I'll close out this issue.
