### ISSUE TITLE
website that connects to sql

### ISSUE THREAD

**Issue by TwoTwenty** [fboender/ansible-cmdb#174]
This is a enhancement request.
I do not expect this, and thank you for what ansible cmdb already is. 

it would be nice host the same webpages that fancy html does but with a sql database backend populated with the sql data dump from ansible-cmdb.

**Comment by fboender** [comment]
Hi TwoTwenty,

I've thought about this in the past, but it's going to entail a lot of work. Ansible's fact output is not particularly structured, nor is it consistent across operating systems. I've worked around this in Ansible-cmdb by simply recursively dumping most facts without looking at the exact structure. Writing this information to an SQL database would require a large sanitation step to fix up all the facts.

I'm afraid that's out of scope for Ansible-cmdb. What you're suggesting would be an entirely new project; quite different from what Ansible-cmdb does right now.

So, as you probably already guessed, I'm not going to implement this feature request, unfortunately.

Thank you for the feature request, and I hope you'll still find Ansible-cmdb useful in its current state!
