### ISSUE TITLE
ImportError: No module named ansiblecmdb on a fresh install 

### ISSUE THREAD

**Issue by ShalbafZadeh** [fboender/ansible-cmdb#178]
in a fresh installation of ansible-cmdb (1.28) via pip , you get this error on all ansible-cmdb commands 
```
[reza:~]$ ansible-cmdb 
Traceback (most recent call last):
  File "/usr/local/bin/../lib/ansiblecmdb/ansible-cmdb.py", line 19, in <module>
    import ansiblecmdb
ImportError: No module named ansiblecmdb
[reza:~]$ ansible-cmdb --debug
Traceback (most recent call last):
  File "/usr/local/bin/../lib/ansiblecmdb/ansible-cmdb.py", line 19, in <module>
    import ansiblecmdb
ImportError: No module named ansiblecmdb
[reza:~]$ 
```

this error happens on both python2 and python3 versions

**Comment by fboender** [comment]
I cannot immediately reproduce this:

    root @ devub16 ~ $ sudo pip install ansible-cmdb
    Collecting ansible-cmdb
      Downloading https://files.pythonhosted.org/packages/e1/41/37a70685dc10b548a5e46bd271bf01d73dd9751bf23230b60e148ab84c7c/ansible-cmdb-1.28.tar.gz (177kB)
        100% |████████████████████████████████| 184kB 798kB/s 
    ...snip...
    Successfully installed MarkupSafe-1.0 ansible-cmdb-1.28 jsonxs-0.6 mako-1.0.7 pyyaml-3.13 ushlex-0.99.1
    root @ devub16 ~ $ ansible-cmdb --version
    ansible-cmdb.py v1.28

Can you let me know:

* The exact command you used to install Ansible-cmdb
* Your OS and version
* The output of `sudo pip -V`

**Comment by ShalbafZadeh** [comment]
tried again and it seems to be fixed
sorry to bother 
thank you very much for your help

**Comment by jingtong-liu** [comment]
I have install Ansible-cmdb through `pip3 install ansible-cmdb`, and restart my ubuntu. It still `ImportError: No module named ansiblecmdb`
