### ISSUE TITLE
Error for hosts not in a group

### ISSUE THREAD

**Issue by coryrwagner** [fboender/ansible-cmdb#18]
Hosts that are not in a group cause an error like this:
```
Traceback (most recent call last):
  File "/usr/local/bin/ansible-cmdb", line 301, in <module>
    ansible = Ansible(args, options.inventory)
  File "/usr/local/bin/ansible-cmdb", line 29, in __init__
    self.parse_hosts(self.hosts_file)
  File "/usr/local/bin/ansible-cmdb", line 94, in parse_hosts
    raw_groups[cur_group_type].setdefault(cur_group_name, []).append(line)
KeyError: None
```

**Comment by palmerit** [comment]
Being that all hosts (regardless of other groups) end up in a default group called 'all'   maybe the 'all' group should be applied to any host found in the inventory files. This would also match this use-case of hosts not defined in another group?

**Comment by fboender** [comment]
Hey Cory,

I've pushed a fix to the master branch that should fix this. Can you try it out to see if it works for you?

@palmerit Not a bad idea, but I found a simpler solution. I might still create a group 'all' in the future though.
