### ISSUE TITLE
Processing and displaying ansible local facts

### ISSUE THREAD

**Issue by marcinpraczko** [fboender/ansible-cmdb#180]
Would be very nice to add processing local facts (which ansible is reading from /etc/ansible/facts.d).
This way som playbook can be run to configure server and then this can be returned to report whether server has been configured with this or not.

**Comment by fboender** [comment]
Hi Marcin!

Ansible-cmdb already has you covered! The host's local facts are shown in the 'Host local facts' section of the host details. I'm currently looking into a method of enabling those facts (and others) in the Host overview (the table of hosts).

Is that what you were looking for, or did I misinterpret your feature request?

**Comment by marcinpraczko** [comment]
Hi, this is exectly what I am looking for as you mentioned. Didn't know that is already covered. 
I am happy to help with this project (I know python) and have some ideas. However I am not good with HTML / CSS / JS. I think I can help with some argument line for example which ansible-facts should be proceeded and you can find the way how to present this in HTML. For example I noticed that there is  `--columns` arguemnt - IMHO we can adjust this to be more flexible. 
I will let you know when I will find a bit of time for small improvments (Small changes / MRs) and we can improve ansible-cmdb. If you are OK with this.

**Comment by fboender** [comment]
>  For example I noticed that there is --columns arguemnt - IMHO we can adjust this to be more flexible.

Yes, I'm trying to figure out a way to make it easier for people to add custom columns. 

> I will let you know when I will find a bit of time for small improvments (Small changes / MRs) and we can improve ansible-cmdb. If you are OK with this.

Absolutely! If you find some time, drop me a line at ferry.boender (AT) gmail DOT com to discuss what you have in mind!
