### ISSUE TITLE
Mako issue?

### ISSUE THREAD

**Issue by SoulOfCinder** [fboender/ansible-cmdb#183]
$ ansible-cmdb --debug
Traceback (most recent call last):
  File "/usr/bin/ansible-cmdb.py", line 18, in <module>
    from mako import exceptions
ImportError: No module named mako

(First Git post so apologies if this is incorrect)
Fresh install of ansible-cmdb and anything relating to ansible-cmdb outputs this.  Mako is installed and up to date so I am confused as to why when I run ansible-cmdb that it no matter what returns this.  

running "$ sudo ansible-cmdb out/ > overview.html
Error parsing: overview.html: No JSON object could be decoded"

I ran that inside of 

/online_inventory/
                               out/
                               overview.html

Any help would be greatly appreciated.

Thank you!

**Comment by fboender** [comment]
Hi SoulOfCinder!

This usually occurs on systems that have both Python v2 and Python v3 installed. Ansible-cmdb looks up which pythons are available on your system and picks the first one it can find. So it's possible that mako is installed for a different python.

It would be helpful to know:

* Which operating system and version are you using?
* Through which method did you install ansible-cmdb? (source, package, pip?)
* Does your system have multiple Python versions installed?

Here's a few things you can try:

* Try installing ansible-cmdb using a different method. The most reliable should be installing it through pip. (make sure to de-install the currently installed ansible-cmdb first)

    $ sudo pip install ansible-cmdb

* See which version of python ansible-cmdb is using and check whether it has the mako library. Ansible-cmdb uses the 'which' command to figure out which python it'll use, like so:

    $ which python
    /usr/bin/python

Check the version:

    $ /usr/bin/python --version
    Python 2.7.15rc1

See if it has Mako:

    $ /usr/bin/python -c 'import mako'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named mako

Install mako using the pip command that corresponds to the installed python version.

    $ sudo /usr/bin/pip install mako

If the output of "which python" returns something like "/usr/bin/python3" instead, then you should probably install mako with "/usr/bin/pip3 install mako".

Unfortunately there are lots of different reasons for why you're experiencing this problem (welcome to the painful world of python package management), so we might have to try a few different things.

**Comment by RrPpDd** [comment]
Hi @fboender 

I had correctly installed ansible cmdb using python 2.7.5.
=============
[root@localhost ansiblecmdb]# python --version
Python 2.7.5
[root@localhost ansiblecmdb]# 

[root@localhost ansiblecmdb]# python3
-bash: python3: command not found
==========

[root@localhost ~]# **pip install ansible-cmdb**
Collecting ansible-cmdb
  Downloading https://files.pythonhosted.org/packages/1f/6f/18b2b850099a2346271ca1854c32d18143540e7961999d33b9fef55c3216/ansible-cmdb-1.30.tar.gz (179kB)
    100% |################################| 184kB 1.5MB/s 
Collecting mako (from ansible-cmdb)
  Downloading https://files.pythonhosted.org/packages/a6/37/0e706200d22172eb8fa17d68a7ae22dec7631a0a92266634fb518a88a5b2/Mako-1.1.3-py2.py3-none-any.whl (75kB)
    100% |################################| 81kB 2.3MB/s 
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /usr/lib64/python2.7/site-packages (from ansible-cmdb)
Collecting ushlex (from ansible-cmdb)
  Downloading https://files.pythonhosted.org/packages/48/e0/33fa11058c8efc51ba3520ceb85c9fa0c5e42ce414b885fcd5e12132d13b/ushlex-0.99.1.tar.gz
Collecting jsonxs (from ansible-cmdb)
  Downloading https://files.pythonhosted.org/packages/65/62/67257a84338fde1b89fce8b28164364bf2ad6a5a4459a6a890cf497cf721/jsonxs-0.6.tar.gz
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe>=0.9.2 in /usr/lib64/python2.7/site-packages (from mako->ansible-cmdb)
Installing collected packages: mako, ushlex, jsonxs, ansible-cmdb
  Running setup.py install for ushlex ... done
  Running setup.py install for jsonxs ... done
  Running setup.py install for ansible-cmdb ... done
Successfully installed ansible-cmdb-1.30 jsonxs-0.6 mako-1.1.3 ushlex-0.99.1
You are using pip version 8.1.2, however version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[root@localhost ~]# ansible-cmdb 
Usage: ansible-cmdb.py [option] <dir> > output.html

The <dir> argument is mandatory

=======

[root@localhost out]# ansible-cmdb /opt/out/ > /opt/out/system-overview.html
Error parsing: system-overview.20200625135406.html: No JSON object could be decoded
Error parsing: system-overview.html: No JSON object could be decoded


Can you please help?
Thanks,
Rachna Dodia
