### ISSUE TITLE
Simple feature idea

### ISSUE THREAD

**Issue by Noname2244** [fboender/ansible-cmdb#184]
In the search bar you can filter the results, what about adding a simple counter on the number of hits ?
Ie if you search for "prd" you see the total number of prd system, or on site name etc. etc.

**Comment by fboender** [comment]
At the bottom of the Host Overview list, in slightly unreadable light gray, it says:

    Showing 1 to 12 of 12 entries (filtered from 105 total entries)

Is that what you mean?

**Comment by fboender** [comment]
I'm just going to go ahead and assume the info at the bottom of the Host Overview satisfies your needs and close this issue. Mostly because I like closing issues :-)
