### ISSUE TITLE
Feature req. Remove columns 

### ISSUE THREAD

**Issue by Noname2244** [fboender/ansible-cmdb#185]
I'm using only custom columns and you can auto "grey out" the other columns with  the --exclude-cols option, but it would be nice to remove them completely .  To only show the custom columns.

**Comment by fboender** [comment]
I've modified the way `-c` (`--columns`: Show only given columns) works for the html_fancy templates. They now actually do what is expected and remove the columns completely from the output. I don't think anybody was really using the original functionality anyway, but I could be wrong.

I've committed this change to master and will release a new packaged version soon.
