### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'major'

### ISSUE THREAD

**Issue by ilovemysillybanana** [fboender/ansible-cmdb#188]
All commands fail with the same error

```
$ ansible-cmdb --debug
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'tuple' object has no attribute 'major'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'tuple' object has no attribute 'minor'
/usr/local/bin/ansible-cmdb: line 22: [: : integer expression expected
Traceback (most recent call last):
  File "/usr/local/bin/../lib/ansible-cmdb/ansible-cmdb.py", line 30, in <module>
    "newer version.\n".format(sys.version))
ValueError: zero length field name in format
```

I just upgraded to python 2.7.11 and the issue persists, I am on CentOS 6.6 x86-64.

**Comment by fboender** [comment]
V2.7 should be supported. Is Python 2.6 installed somewhere on the system too per chance? Ansible-cmdb is actually a wrapper script that tries to determine the correct Python binary to run. Perhaps it's detecting the wrong version. 

I can provide some instructions later on how to check this.

**Comment by fboender** [comment]
I've done some research and it looks like you're still using an older (v2.6) python. It doesn't support the method of detecting the Python version I was using, so I've fixed that. In your case, you should point your PATH to the correct Python location. For example, if you've installed Python v2.7 in /usr/local/bin/, you should change your path from something like:

    export PATH="/usr/bin:/bin:"

to:

    export PATH="/usr/local/bin:/usr/bin:/bin"

The first dir in PATH must have the python v2.7 binary.

**Comment by fboender** [comment]
I've updated the wrapper script so it tries every python interpreter found on your system. It will still need to be in your python, but now it no longer matters where in your path it is, as long as a v2.7+ version is found anywhere.

Can you try the latest master branch to see if it works for you now? I've also added some more debug information that shows which interpreters it tried.
