### ISSUE TITLE
html display GiB > GB

### ISSUE THREAD

**Issue by CalinDee** [fboender/ansible-cmdb#196]
Hi Guys,
Is there any way to alter the html presentation to switch between the usage of MiB/GiB/TiB to MB/GB/TB?

A trivial thing, I know, however I have not been able to locate any switches/flags that do so.

**Comment by fboender** [comment]
Hi CalinDee,

Currently the only way is to create a custom template. It's not that much work. Take a look at [the documentation](https://ansible-cmdb.readthedocs.io/en/latest/usage/#custom-templates). Basically, you'll want to make a copy of the html_fancy template (this is explained in the documentation) and search and replace "1024.0" to "1000" I think.
