### ISSUE TITLE
Mounts are outputted twice

### ISSUE THREAD

**Issue by melbarrett** [fboender/ansible-cmdb#197]
I'm running into a problem with some custom columns, that I noticed is also affecting one of the default columns, 'Disk Usage'.

Essentially, the [template file](https://github.com/fboender/ansible-cmdb/blob/master/src/ansiblecmdb/data/tpl/html_fancy_defs.html#L642) loops over `jsonxs(host, ansible_facts.ansible_mounts, default=[])`, and prints out the disk usage for each mount. But for some reason, the actual column lists every mount twice.

In the overview, this is in disk usage column:

<img width="598" alt="Screen Shot 2019-05-29 at 10 40 49 AM" src="https://user-images.githubusercontent.com/5905261/58570849-4cb33500-81fe-11e9-8470-7532a237f065.png">

The output is repeated. I don't think it's happening inside the html_fancy_defs.html file, as if you look at the highlighted section, all 6 disks aren't sorted. It's the 3 sorted disks, followed by the same 3 sorted disks.

I checked the JSON file as well, and as I expected the correct number of mounts is showing up there:

```
    "ansible_mounts": [
      {
        "block_available": 217236649,
        "block_size": 4096,
        "block_total": 262140923,
        "block_used": 44904274,
        "device": "/dev/xvda2",
        "fstype": "xfs",
        "inode_available": 1043702861,
        "inode_total": 1048573888,
        "inode_used": 4871027,
        "mount": "/",
        "options": "rw,relatime,attr2,inode64,noquota",
        "size_available": 889801314304,
        "size_total": 1073729220608,
        "uuid": "379de64d-ea11-4f5b-ae6a-0aa50ff7b24d"
      },
      {
        "block_available": 262007253,
        "block_size": 4096,
        "block_total": 262015489,
        "block_used": 8236,
        "device": "/dev/xvdg1",
        "fstype": "xfs",
        "inode_available": 524286973,
        "inode_total": 524286976,
        "inode_used": 3,
        "mount": "/data1",
        "options": "rw,noatime,nodiratime,attr2,inode64,noquota",
        "size_available": 1073181708288,
        "size_total": 1073215442944,
        "uuid": "02067dfc-9395-44db-8836-8c2ad7a780b9"
      },
      {
        "block_available": 255154321,
        "block_size": 4096,
        "block_total": 262015489,
        "block_used": 6861168,
        "device": "/dev/xvdf1",
        "fstype": "xfs",
        "inode_available": 1048548832,
        "inode_total": 1048573952,
        "inode_used": 25120,
        "mount": "/data0",
        "options": "rw,noatime,nodiratime,attr2,inode64,noquota",
        "size_available": 1045112098816,
        "size_total": 1073215442944,
        "uuid": "a3e96ce8-70e3-4f3d-a3ab-b1497ab4d8c3"
      }
    ],
```

Is this isolated to my environment? I checked the HTML example overview file, and that doesn't seem to have the repeated mount issue I'm running into. We're not utilizing a custom template file, I'm struggling to understand why the disk usage column is misbehaving.

**Comment by melbarrett** [comment]
Nevermind, this is our own problem, which is in the facts.yml file. We wrap the `ansible -m setup --tree out/ all` command into a playbook that manually calls the setup module. That interacts with a callback plugin that makes sure the tree structure is generated.

The point is, the ansible-playbook command collects facts automatically, but then we call setup in the playbook to trigger our plugin. So our output directory had a Gathering Facts directory and setup directory, with files that had the exact same information. Then the html file would find ansible_facts.ansible_mounts in both directories, causing the sorted output to be printed twice.

Should've tried a bit longer before submitting this issue, apologies for any inconvenience!

**Comment by fboender** [comment]
> Should've tried a bit longer before submitting this issue, apologies for any inconvenience!

No problem at all! Thanks for putting in the time to figure out what was causing the problem.
