### ISSUE TITLE
Sorting Output

### ISSUE THREAD

**Issue by bjmaynard01** [fboender/ansible-cmdb#200]
When outputting to CSV or txt, is there a way to sort the output by a given column?

**Comment by fboender** [comment]
There's not such option in ansible-cmdb, but the output is CSV, so there are many tools that can do this. One of them is csvkit's "csvsort" util (https://csvkit.readthedocs.io/en/latest/tutorial/2_examining_the_data.html#csvsort-order-matters)

Or you can do it on the commandline with default unix tools:

    $ head -n1 cmdb.csv > cmdb_sorted.csv
    $ tail -n+2 cmdb.csv  | sort -t , -h -k 2 >> cmdb_sorted.csv

The example above first puts the header line with the column names in a new file "cmdb_sorted.csv". The second command sorts the rest of the file on the second column ("OS" in this case) and appends the output to the cmdb_sorted.csv file.

Hope that helps!
