### ISSUE TITLE
ansible-cmdb doesnt read ansible facts for custom coloumns

### ISSUE THREAD

**Issue by Ondjultomte** [fboender/ansible-cmdb#205]
Custom coloumns:

```
 `~/playbooks$ cat cust_cols.conf
 [
         {
                 "title": "Hostname",
                 "id": "hostname",
                 "sType": "string",
                 "visible": True,
                 "jsonxs": "ansible_net_hostname"
         },
         {
                 "title": "Model",
                 "id": "modeltype",
                 "sType": "string",
                 "visible": True,
                 "jsonxs": "ansible_net_model"
         },
         {
                 "title": "IOS Version",
                 "id": "iosversion",
                 "sType": "string",
                 "visible": True,
                 "jsonxs": "ansible_net_version"
         },
         {
                 "title": "Serialnumber",
                 "id": "serialnumber",
                 "sType": "string",
                 "visible": True,
                 "jsonxs": "ansible_net_serialnum"
         }
 ]
 `
```

Ansible facts:
```
`cat 172.16.xx.xx_iosfacts.json
{
    "ansible_facts": {
        "ansible_net_filesystems": [
            "flash:"
        ],
        "ansible_net_gather_subset": [
            "hardware",
            "default"
        ],
        "ansible_net_hostname": "theswitchhostname",
        "ansible_net_image": "flash:/c2960x-universalk9-mz.152-2.E7/c2960x-universalk9-mz.152-2.E7.bin",
        "ansible_net_memfree_mb": 341329,
        "ansible_net_memtotal_mb": 403700,
        "ansible_net_model": "WS-C2960X-48FPS-L",
        "ansible_net_serialnum": "FSERIAL",
        "ansible_net_stacked_models": [
            "WS-C2960X-48FPS-L",
            "WS-C2960X-24PS-L"
        ],
        "ansible_net_stacked_serialnums": [
            "FSERIAL",
            "FSERIAL"
        ],
        "ansible_net_version": "15.2(2)E7"
    },
    "changed": false,
    "failed": false
}`
```

**Comment by Ondjultomte** [comment]
![image](https://user-images.githubusercontent.com/16661547/64611661-440ff480-d3d2-11e9-8fa1-fa77f58ef37c.png)

**Comment by Ondjultomte** [comment]
![image](https://user-images.githubusercontent.com/16661547/64611796-89ccbd00-d3d2-11e9-845e-4469ee79cf3c.png)

**Comment by Ondjultomte** [comment]
fixed,

**Comment by pgmodusbox** [comment]
In my local system it does not show any other details other then IP and RAM, I'm also looking memory and uptime.
What I did is run:
`ansible -i hosts -m setup --tree out/ all --ssh-common-args='-o StrictHostKeyChecking=no' "filter=ansible_hostname*,ansible_nodename*,ansible_machine*,ansible_memory_mb*,ansible_memfree_mb*,ansible_memtotal_mb*,ansible_uptime_seconds*,ansible_all_ipv4_*"`

It displays:
<img width="916" alt="image" src="https://user-images.githubusercontent.com/57621328/152150967-1fa723c5-e3e1-401f-b6a5-8977aa0ed69f.png">

And then I run:
`ansible-cmdb out/ > overview_new.html`

But in the output I do see only IP and RAM, 
<img width="953" alt="image" src="https://user-images.githubusercontent.com/57621328/152150686-8847489d-8f12-4bd1-9dae-1839a87c6736.png">

Also Is there any way in html page I could see only required buttons ( which are green in this image)  not all ?
Please help, I will really appreciate for your support as I have been spending many hours on the same. 
Regards,
Pankaj
