### ISSUE TITLE
total disk value is incorrect 

### ISSUE THREAD

**Issue by Kiran-Dexter** [fboender/ansible-cmdb#209]
{"title": "Disk avail", "id": "disk_avail", "visible": True, "field": lambda h: ', '.join(['{0:0.1f}g'.format(i['size_available']/1048576) for i in host['ansible_facts'].get('ansible_mounts', []) if 'size_available' in i and i['size_available'] > 1])},

**Comment by Kiran-Dexter** [comment]
i need to total the over all Allocated DISK

**Comment by fboender** [comment]
This is in the csv template right? If I understand correctly you want the sum for all the available space for all disks? In that case, you can try this:

```
{"title": "Disk avail", "id": "disk_avail", "visible": True, "field": lambda h: "{0:0.1f}g".format(sum([i['size_available']/1048576000 for i in host['ansible_facts'].get('ansible_mounts', []) if 'size_available' in i and i['size_available'] > 1]))},
```

Hope that helps!
