### ISSUE TITLE
lnclude host services info

### ISSUE THREAD

**Issue by kojix** [fboender/ansible-cmdb#211]
Dear friends,

A request, not an Issue...

It would be great to include as part of the ansible-cmdb output the system services and his status.
This info can be collected using -m service_facts, but I don't know how it colud be added to the regular output collected by -m setup...

**Comment by alpengoloids** [comment]
you would need to dump the outputs to another folder then include it in your ansible-cmdb tpls

`# ansible -i <list_of_host_file> all -m service_facts --tree /var/tmp/out_services`

`# ansible-cmdb -i <list_of_host_file> -t html_fancy /var/tmp/out_setup **/var/tmp/out_services** > output.html`

then via html_fancy_defs.html:
`{"title": "SSHD status",  "id": "sshd",         "func": col_sshd,          "sType": "string", "visible": True},`

then for the col function. something like below:
```
<%def name="col_sshd(host, **kwargs)">
  ${jsonxs(host, 'ansible_facts.services.sshd.state', default='')}
</%def>
```

**Comment by fboender** [comment]
alpengoloids answer is correct as far as I can tell.
