### ISSUE TITLE
SQL output.

### ISSUE THREAD

**Issue by DevEvangit** [fboender/ansible-cmdb#217]
Is it possible and asking how to get the sql template with Server UPTIME and Hardware addresses (MAC) on all Ethernet Interfaces and ALL IP in one SQL output
Template: sql.tpl. 

iam working on this at the moment. 

<%def name="col_mac_adr(host)"><%
  return jsonxs(host,'ansible_facts.get('ansible_default_ipv4', {}.get('macaddress'), default='')

that does not show anything. 
Have the latest version of ansible cmdb.
Hope that someone will help me :-)

**Comment by fboender** [comment]
This does the trick for me:

```
<%def name="col_mac(host)"><%
  return jsonxs(host, 'ansible_facts.ansible_default_ipv4.macaddress', default='')
%></%def>
```

Don't forget to modify the `CREATE TABLE` and `INSERT` statement.
