### ISSUE TITLE
Add output sort order ?

### ISSUE THREAD

**Issue by aadrian** [fboender/ansible-cmdb#222]
Hi,

Is it possible to have a sort order for the output files (all types, even for HTML) ?. 
It doesn't matter which one, but it should be the same between runs.

When this output (e.g. HTML) is saved in a VCS (e.g. GIT) , at the moment it's impossible to diff the infrastructure to see what's changed because the order seems random on every run :(

Thank you.

**Comment by fboender** [comment]
I thought this would be an easy fix I could apply globally, but unfortunately that's not possible due to how the host information is layed out in memory.

I've gone ahead and added sorted output to all the templates except the `json` template. The order should now be the same between runs.
