### ISSUE TITLE
Can I collect the host CPU load data?

### ISSUE THREAD

**Issue by gnosis-xian** [fboender/ansible-cmdb#223]

**Comment by fboender** [comment]
Looks like ansible doesn't make this information available through the default facts. You'll have to set up a custom fact on your hosts. You could do something like this:

```
#!/bin/sh

LOAD=$(cut -d" " -f1-3 /proc/loadavg | sed 's/ /, /g')
echo "{\"load\": $LOAD}"
```

If you put that on your hosts in `/etc/ansible/facts.d/load.sh` and make it executable (`chmod 755 /etc/ansible/facts.d/load.sh`), it'll show up in the host facts under `ansible_facts.ansible_local.load.load` and you can use it in a custom column like this (untested but should be close):

```
    {
        "title": "LoadAvg (15m)",
        "id": "load15",
        "sType": "num",
        "visible": True,
        "tpl": """${ jsonxs(host, 'ansible_facts.ansible_local.load.load[2]', default=-1) }"""
    },
```

Hope that helps!
