### ISSUE TITLE
Missing link to jquery breaks default presentation

### ISSUE THREAD

**Issue by areguera** [fboender/ansible-cmdb#228]
The default index.html file uses online version of jquery-1.10.2.min.js which is not available.
```
    <!-- DataTables assets -->
      <script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.2//js/jquery.dataTables.js"></script>
```
This breaks the main output presentation.

Is there any way to customize the jquery location? or use one available?

Thanks.

**Comment by areguera** [comment]
Just to add more context, ansible-cmdb was installed inside a container using pip. Then, the container is the one used to produce the final output. The `local_js=1` option doesn't seem to solve the problem here because it points to a location inside the container, however the `res_url` may, if it could be changed from the command-line.

**Comment by fboender** [comment]
Hi!

Both `https://code.jquery.com/jquery-1.10.2.min.js` and `https://cdn.datatables.net/1.10.2//js/jquery.dataTables.js` are working just fine for me?

Could the problem be related to [this FAQ entry](https://ansible-cmdb.readthedocs.io/en/latest/faq/#the-output-html-file-doesnt-work-on-other-computers)? How are you accessing the `index.html` that was generated in the container in your browser?

**Comment by areguera** [comment]
Hi @fboender !

The `https://cdn.datatables.net/1.10.2//js/jquery.dataTables.js` works fine, the issue is with `https://code.jquery.com/jquery-1.10.2.min.js`, it starts to redirect and don't return the expected content. Here is a curl example from my workstation:
```
]$ time curl -L https://code.jquery.com/jquery-1.10.2.min.js
curl: (47) Maximum (50) redirects followed

real    0m0.837s
user    0m0.032s
sys     0m0.016s
```

The `index.html` file is produced directly in `/var/www/inventory/`, where it is served using a vhost configuration in apache. The container mounts `/var/www/inventory` as volume, does its work and concludes without any issue. All the inventory information is in the `index.html` file but since jquery 1.10.2 js file fails to load (I assume) the browser doesn't show the table as expected. Once I replaced the URL with another pointing the same js file locally, it worked without any issue.

For example, I created the js directory in `/var/www/html/cmdb/js/` directory. Then, create `index.html` using ansible-cmdb, replace js URLs to use `/js/jquery-1.10.2.min.js` and `/js/jquery.dataTables.js` in `index.html`, access https://inventory/ and it works just fine.

Are you behind a proxy or something that may have `https://code.jquery.com/jquery-1.10.2.min.js` cached?

Best regards.

**Comment by areguera** [comment]
I tried to access the URL `https://code.jquery.com/jquery-1.10.2.min.js` today and it works just fine. The `Maximum (50) redirects followed` issue is no longer present.

So, close this issue. Thank you very much.
