### ISSUE TITLE
CSV template - rendering error after custom facts added

### ISSUE THREAD

**Issue by pierocolla** [fboender/ansible-cmdb#229]
below debug trace
notet that is hard to identify which column / host is the one with missing data
i have tried to remove some column and some hosts.facts, but I was able to idetify problematic data

this is custom template
# cat /usr/lib/ansible-cmdb/ansiblecmdb/data/tpl/skylab_csv.tpl
<%

import sys
import csv
import logging

log = logging.getLogger(__name__)

cols = [
  {"title": "Name",         "id": "name",       "visible": True, "field": lambda h: h.get('name', '')},
  {"title": "Application",  "id": "hosting",    "visible": True, "field": lambda h: host['hostvars'].get('site', '')},
  {"title": "DTAP",         "id": "dtap",       "visible": True, "field": lambda h: host['hostvars'].get('dtap', '')},
  {"title": "Ruoli",        "id": "role",       "visible": True, "field": lambda h: host['ansible_facts'].get('ansible_local', []).get('role', '')},
  {"title": "Sites",        "id": "apache",     "visible": True, "field": lambda h: host['ansible_facts'].get('ansible_local', {}).get('apache_sites', '')},
  {"title": "microservizi", "id": "springb",    "visible": True, "field": lambda h: host['ansible_facts'].get('ansible_local', {}).get('springb', '')},
  {"title": "OS",          "id": "os",          "visible": True, "field": lambda h: h['ansible_facts'].get('ansible_distribution', '') + ' ' + h['ansible_facts'].get('ansible_distribution_version', '')},
  {"title": "IP",          "id": "ip",          "visible": True, "field": lambda h: host['ansible_facts'].get('ansible_default_ipv4', {}).get('address', '')},
  {"title": "CPUs",        "id": "cpus",        "visible": True, "field": lambda h: str(host['ansible_facts'].get('ansible_processor_count', 0))},
  {"title": "Disk total",  "id": "disk_total",  "visible": True, "field": lambda h: ', '.join(['{0:0.1f}g'.format(i['size_total']/1048576000) for i in host['ansible_facts'].get('ansible_mounts', []) if 'size_total' in i and i['size_total'] > 1])},
]

def get_cols():
  return [col for col in cols if col['visible'] is True]

fieldnames = []
for col in get_cols():
  fieldnames.append(col['title'])

writer = csv.writer(sys.stdout, delimiter=',', quotechar='"', quoting=csv.QUOTE_ALL)
writer.writerow(fieldnames)
for hostname, host in hosts.items():
    out_cols = []
    for col in get_cols():
      out_cols.append(col['field'](host))
    writer.writerow(out_cols)
%>

debug trace:
#/usr/bin/ansible-cmdb -d -i /etc/ansible/hosts /var/lib/ansible_server/cmdb/facts/ --template skylab_csv > /var/www/skylab/html/skylab_cmdb.csv
data_dir = /usr/lib/ansible-cmdb/ansiblecmdb/data
tpl_dir = /usr/lib/ansible-cmdb/ansiblecmdb/data/tpl
static_dir = /usr/lib/ansible-cmdb/ansiblecmdb/data/static
inventory files = ['/etc/ansible/hosts']
template params = {'exclude_columns': None, 'data_dir': '/usr/lib/ansible-cmdb/ansiblecmdb/data', 'log': <logging.RootLogger object at 0x7fe9b6d6c450>, 'lib_dir': '/usr/lib/ansible-cmdb/ansiblecmdb/data', 'cust_cols': [], 'version': '1.30', 'columns': None}
Parsing fact dir: /var/lib/ansible_server/cmdb/facts/
Reading host facts from /var/lib/ansible_server/cmdb/facts/

................ omissis .............

Determining type of inventory_path /etc/ansible/hosts
/etc/ansible/hosts is a file. Handle as static inventory file
Inventory path /etc/ansible/hosts is a file. Reading as inventory.
Parsing host vars (dir): /etc/ansible/host_vars
No such dir /etc/ansible/host_vars
Parsing group vars (dir): /etc/ansible/group_vars
No such dir /etc/ansible/group_vars
Whoops, it looks like something went wrong while rendering the template.

The reported error was: KeyError: 'ansible_facts'

The full error was:

    Traceback (most recent call last):
      File "/usr/bin/../lib/ansible-cmdb/ansible-cmdb.py", line 216, in <module>
        output = renderer.render(ansible.get_hosts(), params)
      File "/usr/lib/ansible-cmdb/ansiblecmdb/render.py", line 42, in render
        return self._render_mako(hosts, vars)
      File "/usr/lib/ansible-cmdb/ansiblecmdb/render.py", line 59, in _render_mako
        return template.render(hosts=hosts, **vars)
      File "/usr/lib/ansible-cmdb/mako/template.py", line 443, in render
        return runtime._render(self, self.callable_, args, data)
      File "/usr/lib/ansible-cmdb/mako/runtime.py", line 803, in _render
        **_kwargs_for_callable(callable_, data))
      File "/usr/lib/ansible-cmdb/mako/runtime.py", line 835, in _render_context
        _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
      File "/usr/lib/ansible-cmdb/mako/runtime.py", line 860, in _exec_template
        callable_(context, *args, **kwargs)
      File "/usr/lib/ansible-cmdb/ansiblecmdb/data/tpl/skylab_csv.tpl", line 1, in render_body
        <%
      File "/usr/lib/ansible-cmdb/ansiblecmdb/data/tpl/skylab_csv.tpl", line 1, in <lambda>
        <%
    KeyError: 'ansible_facts'

The output is probably not correct.

!!! This is probably a problem with missing information in your host facts

**Comment by eldho-varghese** [comment]
Hi pierocolla 

I'm also struggling export the static date into a csv file. It is able to create the colums but not fetching the data. Have you able to fix it ?

**Comment by pierocolla** [comment]
Hi Eldho
thanks for your answer and excuse me for my delay to reply
default template is working, but I need to add some column, and my costum
template fail on some raw
but also I find it difficult to identify which is the server with 'bad' data
I have tried to delete one server.fact at once, but is a very time
consuming task

is my template the cause, may be don't manage correctly empty data?

thanks
best regards
piero

Il giorno lun 8 mar 2021 alle ore 09:18 Eldho Varghese <
***@***.***> ha scritto:

**Comment by eldho-varghese** [comment]
Hi Pierocolla,

I came across a custom csv work related to ansible cmdb on https://gitlab.com/sjugge/ansible/ansible-cmdb-template-csv/-/blob/master/csv-extended.tpl
I modified the csv.tpl with the above one and it is working fine. However I want to export a few more columns into to csv by modifying the csv.tpl.  I have created host_vars for each host in the inventory an it contain following data

owner: Scott
environment: Qual
hostname: server01
description: Application Server
sys_admin: Eldho Varghese

I am able to display these information in the HTML fancy page. However, adding the additional columns into csv.tpl is giving me empty columns.  

{"title": "Owner",            "id": "owner",            "visible": True, "field": lambda h: host['hostvars'].get('owner', '')},
{"title": "Environment",            "id": "environment",            "visible": True, "field": lambda h: host['hostvars'].get('environment', '')},
{"title": " Description ",            "id": " description ",            "visible": True, "field": lambda h: host['hostvars'].get('description', '')},
{"title": " Sys_Admin ",            "id": " sys_admin ",            "visible": True, "field": lambda h: host['hostvars'].get('sys_admin', '')},

Would you be able to help me here ?  How do I fetch these values into csv ? Looks like my above python code need a tewak

Thanks
Eldho Varghese

**Comment by pierocolla** [comment]
Hi Eldho
also for me HTML template is working and CSV is weakness
but I am not a python guru, so I can't help to troubleshoot this issue
thanks

ciao
piero

Il giorno ven 26 mar 2021 alle ore 10:12 Eldho Varghese <
***@***.***> ha scritto:

**Comment by kfiresmith** [comment]
So after a bunch of trial and error, I've learned how this works for the most part, and have documented some notes on how to do this, at https://github.com/kfiresmith/ansible-cmdb-examples - perhaps this can help others in this thread who have had a hard time with the CSV template?
@pierocolla  @eldho-varghese ^^

**Comment by eldho-varghese** [comment]
@kfiresmith 
I have looked at the code, I have tried the same and the csv export has the column with empty data.  It is not getting any data which defined in the host_vars of each hosts. 

Have you tested this successfully ?

Thanks
Eldho Varghese

**Comment by kfiresmith** [comment]
Hello Eldho,
I wrote a detailed example for you:
https://github.com/kfiresmith/ansible-cmdb-examples

Please copy my example and adapt for your specific columns.

You probably want to diff your column declaration with my example to see the subtle difference in how the syntax works to declare a specific custom group or host var.

**Comment by fboender** [comment]
@pierocolla @eldho-varghese Did you manage to fix your problems? If not, could you open a new issue in the bug tracker? This issue has a bit too much different things going on I feel.

@kfiresmith 

> Ansible-CMDB is widely used, critically important, and largely abandoned by it's maintainer AFAICT :/

Yeah sorry about the lack of support and maintenance. I've been dealing with some personal problems and had extremely low motivation working on any of my open source projects. But to clarify: we're still using ansible-cmdb professionally at my job, so if it breaks it *will* be fixed. I'm currently picking development up again. That'll focus on maintenance for a while, to get rid of the backlog of issues, PRs and technical debt.

> So instead of submitting another ignored PR

If you still feel up to it, any PRs that build out the documentation would be greatly appreciated (and merged quickly).

On https://github.com/kfiresmith/ansible-cmdb-examples you mention: "To gain on-par capability to the html_fancy template, add this block". Would it be okay if I added these columns to the default csv template? I think it should be alright under the GPL, but just to be sure I'd like your permission.

I'm closing this issue since it's been so long, I have no idea what the current status is for the problems mentioned here. If you're still experiencing issues, please file a new bug!

**Comment by eldho-varghese** [comment]
@fboender Yes.. exporting content of host_vars and group_vars issue has been fixed. After fixing the csv template, I made the silly mistake by not defining the inventory file while running the ansible-cmdb command. SO it was not reading the host_vars files :(
Thanks to @kfiresmith  for the csv.tpl entries.

**Comment by fboender** [comment]
@eldho-varghese Nice! Glad to hear you got it working.

**Comment by kfiresmith** [comment]
Hello @fboender  - I'm so glad to hear you are doing better!  
For any of my informal contributions, yes please feel empowered to adapt and absorb them however you might see fit within the project!   Attribution of some sort is always nice for my online presence, but not at all required.

I'd love to submit PRs for the documentation at some point.
