### ISSUE TITLE
Is it possible to add additional & custom columns to the CSV template?

### ISSUE THREAD

**Issue by kfiresmith** [fboender/ansible-cmdb#231]
Hi Folks,
The CSV template is of limited use without core fields like 'comment' and 'dtap'.  I don't understand the template very well but tried to add comment as a column and wasn't able to manage it.

Further, the CSV template could be much more useful if there was a recipe for adding static facts and Ansible custom facts from /etc/ansible/facts.d to it, but this is only covered on html_fancy.  

Any help with figuring out how to add this capability would be much appreciated.  

Thanks!

**Comment by rajeshbahl** [comment]
There are times when we specifically need the details in CSV/excel format - e.g. sharing some information for audit purposes.
Will be really helpful if we could add same columns as are existing in html template. 

Any help would be greatly appreciated.

Thanking in Advance

**Comment by kfiresmith** [comment]
So after a bunch of trial and error, I've learned how this works for the most part, and have documented some notes on how to do this, at https://github.com/kfiresmith/ansible-cmdb-examples.

@rajeshbahl  - please see the above link for more information on how this stuff seems to work.
