### ISSUE TITLE
Add documentation for make release

### ISSUE THREAD

**Issue by rndmh3ro** [fboender/ansible-cmdb#26]
Dependencies on Ubuntu 12.02 are:
- git
- make
- python-markdown
- zip
- fakeroot
- alien

A variable `REL_VERSION` has to be inserted into the Makefile with an arbitrary value?

Am I missing something?

**Comment by fboender** [comment]
I think that's all of the dependencies yes. Building a release can be done with:

    $ sudo make release REL_VERSION=1.5

It'll put packages in the root of the repo.

**Comment by rndmh3ro** [comment]
What do you mean by putting them in the repo? The actual sources? Or the documentation to install the packages?

**Comment by fboender** [comment]
I mean that `make release` will put the built packages (.deb. .rpm, .tar.gz, .zip) in the same directory as the Makefile. Just a little FYI, you don't have to do anything with that information :-)

**Comment by rndmh3ro** [comment]
I noticed that, when building an rpm, thanks! :)

**Comment by fboender** [comment]
Thanks again for the changes Sebastion!

**Comment by rndmh3ro** [comment]
You're welcome, thanks for the awesome tool!
