### ISSUE TITLE
README.md Extending example variables not in overview.html

### ISSUE THREAD

**Issue by ron-h** [fboender/ansible-cmdb#28]
I have used the extend example according to your README.md and specified both directories out/ and out_cust/  when generating the output. But the custom (software) variables didn't show up in the overview.html.

**Comment by fboender** [comment]
Hey ron-h!

Thanks for your bug report. I've verified that this is indeed not working. I'm going to write a bug fix for this tomorrow!

Regards,

Ferry

**Comment by ron-h** [comment]
Nice :) Keep up the good work!

**Comment by fboender** [comment]
Hey!
 Sorry for the late reply. I've pushed a fix to the master branch. It should work now.

**Comment by fboender** [comment]
I'm going to close this issue. If you find out that the fix I've implemented doesn't work for you, please re-open the issue!
