### ISSUE TITLE
ansible-cmdb fails on certain host definitions.

### ISSUE THREAD

**Issue by mdmallardi** [fboender/ansible-cmdb#32]
I was hoping to use ansible-cmdb to get a visualization of my corporate environment, with the custom variables we use.  However, when I try and use ansible-cmdb with our /etc/ansible/hosts inventory file, it bombs out pretty spectacularly.

$ wc -l /etc/ansible/hosts
1673 /etc/ansible/hosts

$ ansible-cmdb out/ -i /etc/ansible/hosts > cmdb.html
Traceback (most recent call last):
  File "/usr/bin/ansible-cmdb", line 454, in <module>
    ansible = Ansible(args, options.inventory, options.fact_cache, debug=options.debug)
  File "/usr/bin/ansible-cmdb", line 352, in __init__
    self.parse_hosts_inventory(self.hosts_path)
  File "/usr/bin/ansible-cmdb", line 373, in parse_hosts_inventory
    hosts_parser = AnsibleHostsParser(hosts_contents)
  File "/usr/bin/ansible-cmdb", line 66, in __init__
    for hostname in self.get_distinct_hostnames():
  File "/usr/bin/ansible-cmdb", line 206, in get_distinct_hostnames
    hostnames.extend(self.group_get_hostnames(section['name']))
  File "/usr/bin/ansible-cmdb", line 271, in group_get_hostnames
    hostnames.extend(self.expand_hostdef(entry['name']))
  File "/usr/bin/ansible-cmdb", line 314, in expand_hostdef
    start, end = pattern.split(':')
ValueError: too many values to unpack

Any help on this would be appreciated.  Thanks.

**Comment by fboender** [comment]
Hi Malcolm!

Thanks for the bug report!

I don't think it's an issue with your hosts file being too large. The "too many values to unpack" is kind of misleading in that regard ;-) Ansible is trying to parse one of the ranged hostnames (e.g. "foo[0:3].bar.com") and failing because it's expecting a colon. 

Could you send your hosts file to my email address (ferry.boender@gmail.com) so I can have a look at it? I will keep it completely confidential. If that's not an option, please let me know so I can figure out a different way to find out which hosts definition is causing the problem.

Regards,

Ferry

**Comment by mdmallardi** [comment]
Thank you for your help, this was indeed some issues with our inventory file.  We've resolved these internally

**Comment by fboender** [comment]
Nice! Could you tell me what the issue was? I should probably skip hosts that fail instead of just failing altogether. At the very least ansible-cmdb should mention the host with the problem.

I'm going to change the title of this bug and reopen it so I can fix that.

**Comment by mdmallardi** [comment]
It was as you suspected:
we had host definitions like this:
d393sv-vmnginx[1:2], it was failing on those.  When we split things out, it worked.

**Comment by mdmallardi** [comment]
Silly close button to the left, bad github, bad!

**Comment by fboender** [comment]
d393sv-vmnginx[1:2] is probably a valid host definition thought, right? ansible-cmdb should handle it properly than, so the bug report still is valid. I'll write up a fix soon. Thanks for your input Malcolm!

**Comment by mdmallardi** [comment]
Quite welcome!  Yes, it is valid, but not widely in use in our environment.

**Comment by fboender** [comment]
I can't seem to reproduce the problem with a host definition of "d393sv-vmnginx[1:2]", but I get the same error if there is more than one pattern in the host definition (e.g. "db[0:2].app[0:2].foo.com"). Did you happen to have a host definition like this?

**Comment by mdmallardi** [comment]
I had a host definition more along the lines of:
d393sv-vmnginx[1:2:3], that may have set it off.

On Tue, Sep 22, 2015 at 1:56 PM, Ferry Boender <notifications@github.com>
wrote:

> I can't seem to reproduce the problem with a host definition of
> "d393sv-vmnginx[1:2]", but I get the same error if there is more than one
> pattern in the host definition (e.g. "db[0:2].app[0:2].foo.com"). Did you
> happen to have a host definition like this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fboender/ansible-cmdb/issues/32#issuecomment-142365004>
> .
>



-- 
Malcolm D. Mallardi

**Comment by fboender** [comment]
ansible-cmdb now shows an error on unparsable host definitions and skips them. Host definitions such as "db[0:2].app[0:2].foo.com" are properly expanded.
