### ISSUE TITLE
Feature request: support dynamic inventories

### ISSUE THREAD

**Issue by azimut** [fboender/ansible-cmdb#33]
Example output of a dynamic inventory script. Where IMAP is a group name, ipaddr a host variable and virt16.example.com a host.

```
{
    "IMAP": {
        "hosts": [
            "virt16.example.com"
        ]
    },
    "_meta": {
        "hostvars": {
            "virt16.dte3.netsol.com": {
                "ipaddr": "1.1.1.1"
            }
        }
    }
}
```

**Comment by fboender** [comment]
Thanks, I'm going to implement a way of handling dynamic inventories. It might take a few days, as I'm kind of pressed for time at the moment.

**Comment by fboender** [comment]
Hey Azimut!

I've commited a set of changes that implement dynamic inventory scanning. I had to implement it against your example, examples from the Ansible documentation and the (rather broken) virtualbox dynamic inventory contrib script. It works for me, but most of the stuff I tested against has been basically mockups.

Can you give it a test spin; see how it works out for you? You'll have to clone the repo, as there's no packaged release with the changes yet.

Thanks for the suggestion!

Regards,

Ferry

**Comment by smiller171** [comment]
Hey, I just stumbled across this. I think I'll give it a shot against my 100+ node dynamic inventory this week

**Comment by fboender** [comment]
Hey Scott!

Please do! I'm curious if I got it right. ;-)

Thanks!

**Comment by azimut** [comment]
Thanks for you work! Somehow it's not working for me. Should this work when a directory is passed to the ```-i``` argument and a dyn inventory is present on that dir?

**Comment by fboender** [comment]
No, the argument to -i should point directly to the script itself. Is what you describe supported by Ansible? I don't think I read that in the docs, but I could have missed it. In that case, I'll implement it.

**Comment by azimut** [comment]
Yup, it's here [using-multiple-inventory-sources](https://docs.ansible.com/ansible/intro_dynamic_inventory.html#using-multiple-inventory-sources):
> ... When doing so, it is possible to mix both dynamic and statically managed inventory sources in the same ansible run. Instant hybrid cloud! </br>

Thanks again!

**Comment by fboender** [comment]
Alright, I'll fix this so multiple inventory sources are supported. Thanks!

**Comment by smiller171** [comment]
@fboender if it doesn't already, you should check the ansible configuration for the default inventory path.

**Comment by fboender** [comment]
Multiple inventory sources are now supported in the latest master. I'm going to close this issue. If it turns out something doesn't work properly, please re-open it or create a new issue. Thanks!

@smiller171 I will create a new feature request for that. It's a good idea, since Ansible itself also doesn't need to be pointed to the inventory path.

**Comment by azimut** [comment]
@fboender Thanks, it works for me.

**Comment by fboender** [comment]
@azimut Thanks for the feedback!
