### ISSUE TITLE
automatic testing and release

### ISSUE THREAD

**Issue by smiller171** [fboender/ansible-cmdb#35]
It would be useful to have an automated testing and release setup so that the latest features can be tested more easily. I could help you set this up in Travis pretty easily.

**Comment by fboender** [comment]
Hey Scott,

Thanks for the offer! Given the current size of the project and the number of core committers (me ;-) I don't really think it's worth the effort to maintain another build system. The Makefile serves me fine right now. As for testing the latest features by end-users; I'd rather they use released packages. If they still wish to run against master, that's their choice of course, but I don't want to have to provide support for unreleased features.

**Comment by smiller171** [comment]
Typically it's better not to merge to master until code is ready for release, and Travis would do your builds for you (using your makefile)
