### ISSUE TITLE
error on creation of overview.html

### ISSUE THREAD

**Issue by merlin-tc** [fboender/ansible-cmdb#45]
I am getting the following error when trying to import all my hosts:
./ansible-cmdb test/ > overview.html
Traceback (most recent call last):
  File "./ansible-cmdb", line 84, in <module>
    sys.stdout.write(mytemplate.render(hosts=ansible.hosts, **params))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 488629: ordinal not in range(128)

I tracked that down to an fstab definition containing the German umlaut "ü".
This is an example, the problem is in the "device" line.

            {   
                "device": "//share/Prüfhinweise",
                "fstype": "cifs",
                "mount": "/home/pflegeanwendung/mounts/ake",
                "options": "rw,relatime,vers=3.0,sec=ntlmssp,cache=strict,file_mode=0660,dir_mode=0770,nounix,mapposix,rsize=65536,wsize=65536,actimeo=1",
                "size_available": 840464404480,
                "size_total": 7696581394432,
                "uuid": "NA"
            },

**Comment by fboender** [comment]
Hey!

I just committed some changes that should fix this. Can you check if it works for you now?

**Comment by merlin-tc** [comment]
Wow, that was fast!
And yes, it's fixed. All 160 hosts are imported.
Thanks a lot!

**Comment by fboender** [comment]
Thanks for the bugreport!

**Comment by fboender** [comment]
Hi merlin-tc,

I've commited a more correct fix for this problem. Can you verify that it still works properly?

**Comment by merlin-tc** [comment]
Yes, it's still working properly.

**Comment by fboender** [comment]
Thanks merlin-tc!
