### ISSUE TITLE
Add search terms to get URL

### ISSUE THREAD

**Issue by arturmartins** [fboender/ansible-cmdb#46]
Hi,

It would be great if it would be possible to add the search terms to the URL. Example: https://cmdb/?search=xen%20x86_64

Bonus: have a URL clipboard copier at the side of the search box to get the URL with search terms.

Reference: http://papermashup.com/read-url-get-variables-withjavascript/

**Comment by fboender** [comment]
Hey Artur

Great idea! I've just pushed a commit for the searching. You can now do (for example): "cmdb.html?search=Ubuntu".

**Comment by fboender** [comment]
I've pushed a change that put a star with a direct link to the search results next to the input box. This allows you to right-click on the start and select "Copy URL" to copy the URL. Making a direct "Copy to clipboard" function would require flash or very recent javascript, so this seemed like a good compromise. The host headers are now also links, so you can directly link to a specific host.

**Comment by arturmartins** [comment]
Great stuff @fboender :+1: Many thanks for this.

**Comment by fboender** [comment]
You're welcome! It was a great idea for a feature!

**Comment by arturmartins** [comment]
Thanks :) 

To be honest, I think the star does not communicate the feature intention. At work, no one actually noticed it. Perhaps an icon like this would be more efficienthttps://www.iconfinder.com/icons/16160/clipboard_sign_icon#size=16 ?

**Comment by fboender** [comment]
I agree completely that the icon doesn't convey the right meaning. I was reluctant to include another image asset, since they need to work correctly over http, https and locally. So it's actually a bit of a pain to include icons. I'll see what I can do to make it better. Perhaps include it directly as data in the CSS. I've open issue #52 for this.

**Comment by fboender** [comment]
Hey Artur!

I've pushed a change which replaces the star icon with a real link icon. Can you check it out; see what you think?

Regards,

Ferry

**Comment by arturmartins** [comment]
Amazing :+1: A see a lot more usage now.
