### ISSUE TITLE
Mem usage

### ISSUE THREAD

**Issue by pathcl** [fboender/ansible-cmdb#53]
How memory usage is measured?

One graph shows ( 7.6 / 9.8GiB ) but I type:

$ free -m
             
total       used       free     shared    buffers     cached

* Mem:         10001       9636        364          0        749       1119
* -/+ buffers/cache:       7767       2233
* Swap:         1905        201       1704

That would be 364MB free.

**Comment by fboender** [comment]
Hey Luis,

There really is no such thing as "free" memory. For example, Both process A  and Bmay report using 2Gb of memory. So you'd be inclined to think they're using 4Gb in total. However, if both are using a shared library that uses 1Gb, the total would be 3Gb. The same is true for sub-processes, which share parts of their parent process' memory, but report as if they're using that memory themselves. Then there's the OS that uses parts of the memory for caching and buffering, but technically that memory can be relinquished to applications when they request them.

But to answer your question, ansible-cmdb merely reports what ansible itself reports. And what ansible reports depends on the ansible version and OS in question. I don't know exactly how ansible comes at the 2.2Gb free, but it appears to be the amount of free mem + free buffers/cache.

**Comment by pathcl** [comment]
@fboender thank you!

**Comment by fboender** [comment]
You're welcome Luis! It wasn't the most helpful answer perhaps, but "free memory" is a *very* hard concept ;-)
