### ISSUE TITLE
Ignore hidden dotfiles

### ISSUE THREAD

**Issue by iAugur** [fboender/ansible-cmdb#54]
Just noting this in case anyone else gets this issue.
If you are running on a MAC and have a .DS_STORE file in the output folder you will get the following error:
```
UnicodeDecodeError: 'utf8' codec can't decode byte 0x80 in position 3131: invalid start byte
```
The solution is to delete these files first.
Maybe ansible-cmdb could have an option to ignore files such as dotfiles.
Or maybe use http://asepsis.binaryage.com/ to stop creating them? - Not tried it yet but might be the solution?

**Comment by fboender** [comment]
Hey George!

Thanks for the bug report. I just pushed a new commit that should fix this issue. It ignores files starting with a dot in the fact output directories.

Regards,

Ferry

**Comment by iAugur** [comment]
Nice - thanks 

Great tool btw ; )

**Comment by fboender** [comment]
Glad you find it useful!
