### ISSUE TITLE
Vmware offline inventory 

### ISSUE THREAD

**Issue by pathcl** [fboender/ansible-cmdb#57]
It would be nice to get info about vmware vm's even if they're powered off. I think this can be done through pyVmomi.

**Comment by fboender** [comment]
Hey Luis!

Getting the actual info is ansible's job. Ansible-cmdb merely parses Ansible data such as host inventories and facts. What you want should be possible with Ansible though. You may want to have a look at Ansible's Dynamic inventory capabilities. Ansible-cmdb can read dynamic inventory output as outlined in https://github.com/fboender/ansible-cmdb#inventory-scanning

Basically you just point the `-i` option to a dynamic inventory script. For example:

    ansible-cmdb -i vmware.py out > cmdb.html

More information on dynamic inventories is available here: http://docs.ansible.com/ansible/intro_dynamic_inventory.html. 

There is a VMware dynamic inventory script available here, but I don't know if it works: https://github.com/ansible/ansible/tree/devel/contrib/inventory

If the above doesn't work for you, it should be possible to write a script that generates ansible fact output from vmware, even if the hosts are not running. That, however, is outside of the scope of Ansible-cmdb.

I hope this helps you in some way!

With kind regards,

Ferry
