### ISSUE TITLE
failure parsing complex variables in inventory file

### ISSUE THREAD

**Issue by dlbewley** [fboender/ansible-cmdb#58]
Using this inventory file
- https://gist.github.com/dlbewley/d7db07edb7fa6da72259

Specifically the variable on line 84
- `openshift_master_identity_providers=[{'name': 'my_ldap_provider', 'challenge': 'true', 'login': 'true', 'kind': 'LDAPPasswordIdentityProvider', 'attributes': {'id': ['dn'], 'email': ['mail'], 'name': ['cn'], 'preferredUsername': ['uid']}, 'bindDN': '', 'bindPassword': '', 'ca': '', 'insecure': 'true', 'url': 'ldap://ldap.example.com:389/ou=people,o=example.com?uid'}]
`

And running like this

- ` ansible-cmdb --inventory=hosts-test --debug -f fact-cache/ > cmdb/overview2.html`

Produces this error

```
 ansible-cmdb --inventory=hosts-test --debug -f fact-cache/ > cmdb/overview2.html
/usr/lib/python2.6/site-packages/pygments/plugin.py:39: UserWarning: Module mako was already imported from /usr/lib/ansible-cmdb/mako/__init__.py, but /usr/lib/python2.6/site-packages is being added to sys.path
  import pkg_resources
  data_dir = /usr/lib/ansible-cmdb/ansiblecmdb/data
  tpl_dir = /usr/lib/ansible-cmdb/ansiblecmdb/data/tpl
  static_dir = /usr/lib/ansible-cmdb/ansiblecmdb/data/static
  Parsing fact dir: fact-cache/
  Reading host facts from fact-cache/ose-ha-etcd-02.example.com
  Reading host facts from fact-cache/ose-ha-master-03.example.com
  Reading host facts from fact-cache/ose-ha-etcd-03.example.com
  Reading host facts from fact-cache/ose-master-01.example.com
  Reading host facts from fact-cache/ose-ha-node-06.example.com
  Reading host facts from fact-cache/ose-ha-node-01.example.com
  Reading host facts from fact-cache/ose-ha-node-03.example.com
  Reading host facts from fact-cache/ose-node-02.example.com
  Reading host facts from fact-cache/ose-ha-node-04.example.com
  Reading host facts from fact-cache/ose-node-03.example.com
  Reading host facts from fact-cache/ose-ha-etcd-01.example.com
  Reading host facts from fact-cache/ose-ha-lb-01.example.com
  Reading host facts from fact-cache/ose-ha-node-02.example.com
  Reading host facts from fact-cache/ose-ha-node-05.example.com
  Reading host facts from fact-cache/ose-node-01.example.com
  Reading host facts from fact-cache/ose-ha-master-02.example.com
  Reading host facts from fact-cache/ose-ha-master-01.example.com
  Traceback (most recent call last):
        File "/usr/bin/ansible-cmdb", line 82, in <module>
            ansible = ansiblecmdb.Ansible(args, options.inventory, options.fact_cache, debug=options.debug)
          File "/usr/lib/ansible-cmdb/ansiblecmdb/ansible.py", line 39, in __init__
            self._handle_inventory(self.inventory_path)
          File "/usr/lib/ansible-cmdb/ansiblecmdb/ansible.py", line 58, in _handle_inventory
            self._parse_hosts_inventory(inventory_path)
          File "/usr/lib/ansible-cmdb/ansiblecmdb/ansible.py", line 85, in _parse_hosts_inventory
            hosts_parser = parser.HostsParser(hosts_contents)
          File "/usr/lib/ansible-cmdb/ansiblecmdb/parser.py", line 44, in __init__
            "Invalid hosts file?\n".format(str(e)))
        ValueError: zero length field name in format
```

**Comment by fboender** [comment]
Hey Dale,

I have confirmed this bug. I'll have to give some thought to a good solution. Thank you for reporting it and I'll try to have a solution as soon as possible.

Regards

Ferry

**Comment by fboender** [comment]
Hey Dale,

I can't find in the Ansible documentation where it says this is allowed in hosts files. It seems fine for playbooks and variable files (http://docs.ansible.com/ansible/intro_inventory.html#splitting-out-host-and-group-specific-data), but it doesn't seem to be allowed officially in hosts files?

**Comment by fboender** [comment]
It seems this is explicitly not allowed / discouraged in the manual:

> If you need to store lists or hash data, or prefer to keep host and group specific variables separate from the inventory file, see the next section.

The next section is http://docs.ansible.com/ansible/intro_inventory.html#splitting-out-host-and-group-specific-data

Perhaps it works right now in Ansible, but I am apprehensive about adding support for undocumented features. Especially since it would require rewriting a large part of the hosts file parsing code ;-)

I suggest you split the variables out in separate files as suggested by the manual.

**Comment by dlbewley** [comment]
I hear what you are saying, but FWIW This format comes from https://github.com/openshift/openshift-ansible which is from RH who are the new Ansible benefactors.

**Comment by fboender** [comment]
You're right, and it does seem to work. I'll re-open this issue and take another look to see if ansible-cmdb can support this.

**Comment by fboender** [comment]
Hey Dale!

I've committed a fix that implements support for this. I had to make some guesses about how it's supposed to work, since it's not really documented.

Thank you for reporting the bug!

Regards

**Comment by dlbewley** [comment]
Thanks for accommodating it. Cheers!
