### ISSUE TITLE
[v1.12] Build instructions for ‘other systems’ incorrect

### ISSUE THREAD

**Issue by sanmai-NL** [fboender/ansible-cmdb#64]
The Makefile does not have an `install` target.

**Comment by fboender** [comment]
Hi Sander,

Those instructions refer to the Makefile found in the .tar.gz downloadable (https://github.com/fboender/ansible-cmdb/releases), not the one in the master branch. I agree it's confusing though. I'll create install and uninstall targets for the main Makefile too.

**Comment by sanmai-NL** [comment]
Great. I was using https://github.com/fboender/ansible-cmdb/archive/1.12.tar.gz , also referred to at https://github.com/fboender/ansible-cmdb/releases/tag/1.12 .

**Comment by fboender** [comment]
Fixed!
