### ISSUE TITLE
RAM and VCPU columns sorting issues

### ISSUE THREAD

**Issue by arturmartins** [fboender/ansible-cmdb#65]
Both columns are sorted by ASCIIbetical order rather numerical order.

I have different servers with different RAM sizes and they are sorted in the following way.

1.0
15.7
2.0
31.6
4.0
8.0

Maybe alphanum can help? http://www.davekoelle.com/alphanum.html

**Comment by fboender** [comment]
Yeah, I've noticed this too. It's annoying. It's a problem with dataTables. I've pushed a fix for this problem to the master branch.

**Comment by fboender** [comment]
Seems to work for me. I'm closing this. If you experience any problems, please let me know! Thanks for the bug report.
