### ISSUE TITLE
-i option doesn't seem to work correctly when using inventory of multiple files. 

### ISSUE THREAD

**Issue by blutgens** [fboender/ansible-cmdb#66]
We chose to break our inventory out into multiple files as it's easier to manage and we can use a simple script that aggregates and builds lists from multiple sources. 

Thus my ansible inventory is made up of approximately 60+ ini style files in a dir. When I pass that dir to -i, groups seems to only be populated with a single group that a given host is a member of, instead of all of them. 

If i concatenate all of my inventory files into a single file, it works just fine with ansible-cmdb.

**Comment by fboender** [comment]
Hi blutgens!

Thank you for the bug report. 

I haven't verified it, but I think you're probably right that this doesn't work properly. I will fix this as soon as possible.

**Comment by fboender** [comment]
Hey blutgens,

I think I've fixed this issue in the latest master branch. Can you verify?

Thanks!
