### ISSUE TITLE
duplicate hosts with same main ip/fqdn

### ISSUE THREAD

**Issue by dmitriykulishenko** [fboender/ansible-cmdb#67]
hosts with ip aliases shown like separate hosts, 
for example, one host with four aliases will shown 4 times, but is has the same main ip and fqdn.

**Comment by fboender** [comment]
Hey Dmitriy!

Just to be clear, this is a feature request, right?

**Comment by dmitriykulishenko** [comment]
as for me, it is more issue than feature.

**Comment by fboender** [comment]
Hi Dmitriy,

I've taken a look at this feature request, and it's going to be difficult to implement. Ansible and ansible-cmdb are built on the fact that a host is uniquely identified by its node name in Ansible, not by IP addresses.

So unfortunately, I won't be implementing this feature. You can take a look at implementing your own template, or you could use the CSV export + Excel or something to do it. 

Regards,

Ferry
