### ISSUE TITLE
Remove external dependencies

### ISSUE THREAD

**Issue by rndmh3ro** [fboender/ansible-cmdb#7]
When hosting the generated output on an internal system, access to internet resources like datatables.net or jquery ist not always possible or preferred.

The resources should be included in the program itself or there should be a option to use the resources locally.

**Comment by fboender** [comment]
As a workaround, you can start a local HTTP server to serve the file with `python -m SimpleHTTPServer`. Browse to http://127.0.0.1:8000 to view it. 

For a more structural solution, I can create a new template 'html_fancy_local' that uses local files.

**Comment by rndmh3ro** [comment]
'html_fancy_local' sounds great!
I could create a PR if you want. 
Create a new directory `/usr/local/lib/${PROG}/static/js`, put the JS-files there and reference them?

**Comment by fboender** [comment]
I was planning on using the new `-p` option to ansible-cmdb to pass a param to the html_fancy template. Something like `-p local=1`. Otherwise we have to maintain two separate but otherwise identical templates.

**Comment by fboender** [comment]
`/usr/local/lib/${PROG}/static/js` sounds good!

**Comment by fboender** [comment]
I've commited a change that lets you generate html_fancy template output with local resources instead of the internet. How to use it is described in the README. Can you check it out, see what you think?

**Comment by rndmh3ro** [comment]
Looks good to me, thanks!
