### ISSUE TITLE
Question: display of facter facts?

### ISSUE THREAD

**Issue by dcj** [fboender/ansible-cmdb#70]
I have facter installed on most of my servers, and have a custom/local facter fact executable as well.

Ansible's setup module calls facter, and the resulting output of ansible -m setup includes my facter info with my custom fact.

In the out directory I create prior to invoking ansible-cmdb, the JSON in the files there includes both the standard and my custom facter_ facts.

AFAICT, ansible-cmdb isn't displaying these facts.

What can change/modify in order to include one/some/all of these additional facts?

**Comment by fboender** [comment]
Hey Don,

Ansible-cmdb already display the local facts from `/etc/ansible/facts.d`, so including facts from facter should be fairly simple. Could you send me a sample via email so I can test it?

Regards,

**Comment by fboender** [comment]
I've just committed Facter facts support for the html_fancy template. There's no filtering yet. I'll have to ponder a bit on how to do that in global way.

Can you check if this works for you?

**Comment by dcj** [comment]
It works!
Thank you!

**Comment by fboender** [comment]
Nice!

I'll look at your other issue tomorrow hopefully.
