### ISSUE TITLE
Extending using out_cust

### ISSUE THREAD

**Issue by abedk** [fboender/ansible-cmdb#71]
Thank you for this project fboender, has lots of promise.

I tried to extend custom facts using the instructions in README.md:
   $ cat out_cust/myhost.com
   {
    "software": [
        "Apache2",
        "MySQL5.5"
      ]
   }

and out/myhost.com  exists with default facts etc...  however after generating the report with 
    ./ansible-cmdb out/ out_cust/ > overview.html

I do not see the custom "software" anywhere... even if I grep for it in the overview.html?

Thank you

**Comment by fboender** [comment]
Hey Abed!

Sorry, the documentation isn't super clear on this. The extended facts are not visible by default in the html_fancy template, except for the "dtap", "comment" and other custom variables. The idea with extended facts is that you can add facts missing from Ansible's generated facts. For example, Ansible reports no memory for certain BSD machines, so you could add them manually in an extended variables file.

For now, if you want your extended facts to show up in the output, you can either modify the template or abuse the fact that the html_fancy template displays "host local facts" by putting the extended information in the `ansible_facts` -> `ansible_local` key:

    {
      "ansible_facts": {
        "ansible_local": {
          "software": [
            "Apache2",
            "MySQL5.5"
          ]
      }
    }

I'm going to implement a new section in the `html_fancy` template specifically for displaying custom facts.

**Comment by fboender** [comment]
Abed,

I've added a "Custom facts" section to the `html_fancy` template that displays custom facts. You can use it like this:

    $ vi custfact.test.local
    {
      "custom_facts": {
        "software": {
          "apache": {
            "version": "2.4",
            "install_src": "backport_deb"
          },
          "mysql-server": {
            "version": "5.5",
            "install_src": "manual_compile"
          },
          "redis": {
            "version": "3.0.7",
            "install_src": "manual_compile"
          }
        }
      }
    }

For this to work the facts must be listed under the custom_facts key.

Generate the overview:

    ./ansible-cmdb out/ out_custom/ > overview.html

The software items will be listed under the "Custom facts" heading.

I've also updated the README to make it more clear how the various fact extending scenarios work. See https://github.com/fboender/ansible-cmdb#extending for more info.
