### ISSUE TITLE
Add ansible-vault support

### ISSUE THREAD

**Issue by azimut** [fboender/ansible-cmdb#73]
On ansible you can encrypt and password protect sensitive files by creating .yml with *ansible-vault*
http://docs.ansible.com/ansible/playbooks_vault.html

I use some of those on the group_vars/

Ansible-cmdb should be aware of them and ignore them.

**Comment by azimut** [comment]
The header of said files is:
```
$ANSIBLE_VAULT;1.1;AES256
```
Followed by strings and strings of numbers.

**Comment by fboender** [comment]
Hey azimut! 

Sorry for the long delay in replying. I've been extremely busy.

I've pushed a commit to the master branch a few days ago that should ignore any invalid files in the group_vars dir. Can you test to see if this works for you?

Thanks!

Regards,

Ferry
