### ISSUE TITLE
Invalid hosts file when using -i switch?

### ISSUE THREAD

**Issue by guybluebat** [fboender/ansible-cmdb#76]
I tried to use the -i switch to read my inventory directory, but I'm getting an error:

Error while parsing hosts contents: 'Traceback (most recent call last):
  File "/usr/lib/ansible-cmdb/ansiblecmdb/parser.py", line 29, in __init__
    self.sections = self._parse_hosts_contents(hosts_contents)
  File "/usr/lib/ansible-cmdb/ansiblecmdb/parser.py", line 95, in _parse_hosts_contents
    name, vars = self._parse_line_entry(line, cur_section['type'])
  File "/usr/lib/ansible-cmdb/ansiblecmdb/parser.py", line 163, in _parse_line_entry
    key_values = self._parse_vars(tokens)
  File "/usr/lib/ansible-cmdb/ansiblecmdb/parser.py", line 209, in _parse_vars
    k, v = token.split('=', 1)
ValueError: need more than 1 value to unpack
'
Invalid hosts file?

My inventory is a combination of static and dynamic, and the group and host vars are organised with folders for each host group/host name, eg:

```
inventory/
|- hosts
|- ec2.py
|- host_vars/
   |- 10.0.5.147/
       |- appdata.yml
   |- 10.0.6.17/
       |- appdata.yml
|- group_vars/
   |- all/
       |- ssh.yml
       |- sudo.yml
   |- web_servers/
       |- apache.yml
       |- nginx.yml
```

Should the -i switch be capable of handling this structure? The docs do indicate that dynamic inventory is supported.

**Comment by fboender** [comment]
Ansible-cmdb currently doesn't understand yaml files as inventory files, at least not in the inventory directories. I'll see about implementing this.

**Comment by fboender** [comment]
Looks like I was wrong and ansible-cmdb *does* support Yaml files in the inventory files. It just doesn't support group_vars yet.

Do you happen to have some yaml in your actual hosts file? Probably a line in there with no '='?

**Comment by fboender** [comment]
To clarify, it seems there's a line in your hosts file that looks something like this?:

    frontend purpose: "web"

Or something? Ansible-cmdb expects each element of the line (except the first one) to be a <key>=<value> pair.

**Comment by fboender** [comment]
I've committed a change in master that should skip any invalid vars defnitions and print the invalid line on stderr. Could you try running against master and report the line that's causing the problem?

Thanks!

**Comment by guybluebat** [comment]
Ok, I pulled the latest commits from master and ran it. I got a huge dump of errors - small sample below:

Unsupported vars syntax. Skipping line: group_by_elasticache_replication_group = True
Unsupported vars syntax. Skipping line: enabled: 'true'
Unsupported vars syntax. Skipping line: transaction_tracer: 'true'
Unsupported vars syntax. Skipping line: leaderboard_processing: True
Unsupported vars syntax. Skipping line: enabled: True

So it looks like it's parsing my ec2.ini configuration file as well as my group and host vars YAML files. I guess the problem is as you say, that it doesn't understand group/host_vars and any other non-standard files in the directory.

**Comment by fboender** [comment]
You can try invoking ansible-cmdb with:

    ansible-cmdb -i /path/to/inventory/hosts /path/to/facts

That should still pick up your hosts_vars directory, but it will skip anything else in the inventory directory.  Unfortunately, ansible-cmdb currenly doesn't support recursive hosts_vars and group_vars directories. I'll create a new ticket to implement that.

**Comment by guybluebat** [comment]
Ok, fair enough. Thanks!

**Comment by fboender** [comment]
The new ticket is here: https://github.com/fboender/ansible-cmdb/issues/81

I'm gonna close this one, since the real problem is just that ansible-cmdb doesn't implement hosts_vars and group_vars properly yet.

Thanks for your bugreport!
