### ISSUE TITLE
Support for the investigation of memory is DDR3 or DDR4?

### ISSUE THREAD

**Issue by ppabc** [fboender/ansible-cmdb#79]
Support for the investigation of memory is DDR3 or DDR4?

**Comment by fboender** [comment]
Hey Robert!

Ansible doesn't gather facts about the type of memory in a system, so I can't include it in ansible-cmdb. 

What you could do is gather [custom facts](http://serverascode.com/2015/01/27/ansible-custom-facts.html) on your machines about the memory type (`dmidecode` should do the trick). The custom facts will be picked up by Ansible and consequently ansible-cmdb. If you want them as a column in the list, you'll have to extend the html_fancy template with a new column. 

Hope that helps!

Regards,

Ferry

**Comment by ppabc** [comment]
Thank you for your help！

**Comment by fboender** [comment]
Sure thing Robert! Let me know if you need any help with implementing this. I'm fairly busy at the moment but I can probably find some time.
