### ISSUE TITLE
IBM Power issue

### ISSUE THREAD

**Issue by beatzuerrer** [fboender/ansible-cmdb#80]
Hello
I would like to generate the inventory collected from IBM-Power Systems. 
Attached the facts file (renamed to tstm1023.txt) and the hosts file (renamed to tstm1023_host.txt)
I run the following:

ansible -m setup --tree /tmp/out/ AIX_oracle_T
/usr/local/bin/ansible-cmdb  -d /tmp/out/ > /tmp/overwiew.html

And get:
data_dir = /usr/local/lib/ansible-cmdb/ansiblecmdb/data
tpl_dir = /usr/local/lib/ansible-cmdb/ansiblecmdb/data/tpl
static_dir = /usr/local/lib/ansible-cmdb/ansiblecmdb/data/static
config_file = /etc/ansible/ansible.cfg
inventory hostfile = None
Parsing fact dir: /tmp/out/
Reading host facts from /tmp/out/tstm1023
Reading host facts from /tmp/out/tstm1036
Reading host facts from /tmp/out/tstm1035
Reading host facts from /tmp/out/tstm1038
template file = /usr/local/lib/ansible-cmdb/ansiblecmdb/data/tpl/html_fancy.tpl
Template params: {'lib_dir': '/usr/local/lib/ansible-cmdb/ansiblecmdb/data', 'version': '%%MASTER%%', 'data_dir': '/usr/local/lib/ansible-cmdb/ansiblecmdb/data', 'log': <logging.RootLogger object at 0x3fffa0bff390>, 'columns': None}
Rendering host overview for tstm1023

Traceback (most recent call last):
  File "/usr/local/bin/ansible-cmdb", line 122, in <module>
    out = mytemplate.render(hosts=ansible.hosts, **params)
  File "/usr/local/lib/ansible-cmdb/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/local/lib/ansible-cmdb/mako/runtime.py", line 803, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/local/lib/ansible-cmdb/mako/runtime.py", line 835, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/local/lib/ansible-cmdb/mako/runtime.py", line 860, in _exec_template
    callable_(context, *args, **kwargs)
  File "/usr/local/lib/ansible-cmdb/ansiblecmdb/data/tpl/html_fancy.tpl", line 549, in render_body
    <td>${col["func"](host)}</td>
  File "/usr/local/lib/ansible-cmdb/ansiblecmdb/data/tpl/html_fancy.tpl", line 0, in col_groups

  File "/usr/local/lib/ansible-cmdb/ansiblecmdb/data/tpl/html_fancy.tpl", line 49, in render_col_groups
    ${'<br>'.join(jsonxs(host, 'groups', default=''))}
TypeError: jsonxs() got an unexpected keyword argument 'default'

Whoops, it looks like something went wrong while rendering the template.

The reported error was: jsonxs() got an unexpected keyword argument 'default'

[tstm1023.txt](https://github.com/fboender/ansible-cmdb/files/367513/tstm1023.txt)
[tstm1023_host.txt](https://github.com/fboender/ansible-cmdb/files/367520/tstm1023_host.txt)

**Comment by fboender** [comment]
Hey beatzuerrer!

Thanks for the bug request. I think I know what's going on. I forgot to include the jsonxs lib in the installer. You probably got an error that it didn't exist and then installed it with pip? The version on the Python Package Index is slightly out of date.

I've commited a fix that should get rid of this problem. Can you try reinstalling Ansible-cmdb from master:

    $ git pull --rebase
    $ sudo make uninstall
    $ sudo make install

Let me know if that fixes the problem!

With kind regards,

Ferry

**Comment by beatzuerrer** [comment]
Hello Ferry

Now it works perfect. Thank you verry much for your help.
Do you have a paypal-account for donations?

Beat Zürrer

Von: Ferry Boender [mailto:notifications@github.com]
Gesendet: Montag, 18. Juli 2016 08:14
An: fboender/ansible-cmdb <ansible-cmdb@noreply.github.com>
Cc: Zürrer Beat (OIZ) <Beat.Zuerrer@zuerich.ch>; Author <author@noreply.github.com>
Betreff: Re: [fboender/ansible-cmdb] IBM Power issue (#80)


Hey beatzuerrer!

Thanks for the bug request. I think I know what's going on. I forgot to include the jsonxs lib in the installer. You probably got an error that it didn't exist and then installed it with pip? The version on the Python Package Index is slightly out of date.

I've commited a fix that should get rid of this problem. Can you try reinstalling Ansible-cmdb from master:

$ git pull --rebase

$ sudo make uninstall

$ sudo make install

Let me know if that fixes the problem!

With kind regards,

Ferry

**Comment by fboender** [comment]
Glad to hear it works! Thanks for reporting this bug.

> Do you have a paypal-account for donations?

Nope. Your bug report and gratitude are enough thanks for me! ;-)

**Comment by beatzuerrer** [comment]
Hello Ferry

Can I ask you a question? I would like to generate a sql-File with the following information’s collected with ansible -m setup --tree /tmp/out/ all

        "ansible_local": {
            "disc": {
                "ADPVO1": "fcs0",
                "ADPVO2": "fcs1",
                "DSKINF": [
                    {
                        "DEVIDE": "6000144000000010300CF4F6E4012890",
                        "DSKNAM": "hdiskpower0",
                        "DSKSIZ": 138105,
                        "DSKVGN": "rootvg",
                        "EMCTYP": "I"
                    },
                    {
                        "DEVIDE": "6000144000000010300CF4F6E401288A",
                        "DSKNAM": "hdiskpower1",
                        "DSKSIZ": 138105,
                        "DSKVGN": "sapallvg",
                        "EMCTYP": "I"
                    },
                    {
                        "DEVIDE": "6000144000000010300CF4F6E401288B",
                        "DSKNAM": "hdiskpower2",
                        "DSKSIZ": 138105,
                        "DSKVGN": "sapallvg",
                        "EMCTYP": "I"
                    },
                    {
                        "DEVIDE": "6000144000000010300CF4F6E401288C",
                        "DSKNAM": "hdiskpower3",
                        "DSKSIZ": 138105,
                        "DSKVGN": "sapallvg",
                        "EMCTYP": "I"
                    }
                ],
                "SLTVO1": 61,
                "SLTVO2": 62
            },

The entry DEVIDE can appear 1 to n times. The sql should look like

    INSERT INTO diskinf (
        name,
        DEVIDE,
        DSKNAM,
        DSKSIZ,
        DSKVGN,
        EMCTYP,
    ) VALUES (
        "tstm1036",
        "6000144000000010300CF4F6E4012890",
        "hdiskpower0",
        "138105",
        "rootvg",
        "I",
    );

for every entry in DSKINF. name is the hostname.

Sorry, I know, that this is a newbie question but I have no clue how to modify the sql.tpl template to bring this to work.
In the attachment I send you the output from the Server.

Beat Zürrer




Von: Ferry Boender [mailto:notifications@github.com]
Gesendet: Dienstag, 19. Juli 2016 09:05
An: fboender/ansible-cmdb <ansible-cmdb@noreply.github.com>
Cc: Zürrer Beat (OIZ) <Beat.Zuerrer@zuerich.ch>; Author <author@noreply.github.com>
Betreff: Re: [fboender/ansible-cmdb] IBM Power issue (#80)


Glad to hear it works! Thanks for reporting this bug.

Do you have a paypal-account for donations?

Nope. Your bug report and gratitude are enough thanks for me! ;-)

**Comment by fboender** [comment]
Hi Beat!

You'd have to create a new table for the diskinf. Look for the CREATE TABLE statement in qry.tpl and copy it. 

Next you'll have to add a loop to write the information. In sql.tpl there is currently a loop: `% for hostname, host in hosts.items()`. This loop goes over each host in your inventory. In this loop, after the INSERT query, you'll want to add another loop that loops over each diskinf entry.. something like this:

    % for hostname, host in hosts.items():
        # Current INSERT query
        % for diskinf in jsonxs(host, 'ansible_local.disc.DSKINF', default=[]):
            # new INSERT INTO diskinf
        % endfor
    % endfor

(Note: I haven't tested the code above; it's just an approximation)

Does this help you get started? If not, let me know and I'll whip up a working version.

With kind regards,

Ferry
