### ISSUE TITLE
Unable to install ansible-cmdb using pip

### ISSUE THREAD

**Issue by ssbarnea** [fboender/ansible-cmdb#83]
As any python package (including ansible itself), I would expect to be able to install `ansible-cmdb` using pip but that's not the case. 

Can you please fix this? pip is a great deployment tool what works very well for ansible and I don't see any reasons for not making this the default way to install and upgrade this too.

**Comment by fboender** [comment]
Hi Sorin!

From the FAQ:

> Python packaging / Pypi?
>
> Python has some of the most horrendous packaging infrastructure I've ever encountered in 25 years of programming. As such, anything related to Python packaging will not be supported.

I currently haven't changed my mind about this. I don't believe pip is the proper way to install programs. Rather, it should be used for python libraries.

**Comment by ssbarnea** [comment]
Probably you have this impression because you don't know that python modules can be executed using a syntax like `python -m flake8` -- most famous python tools and utilities to support this, which works very well (and this approach is not affected by the python based command line tool problems we are facing on OS X or Windows)

PS. If you want I can help with this, it's very easy to adapt.

**Comment by chicks-net** [comment]
If it is so easy, maybe you could show that with a Pull Request.

**Comment by fboender** [comment]
Please don't put in the time, since I don't have the time or inclination to actually incorporate and test it. I did that a few months ago when someone made a pull request for Python packaging, and it bummed me out so much that I decided never to support it.

**Comment by steveholden** [comment]
What a pity you are letting your prejudices (?) keep you out of the mainstream. There are literally tens of thousands of pip-installable packages in PyPI, so the task clearly isn't insurmountable And yet you refuse assistance when it is offered. This seems a little strange.

**Comment by fboender** [comment]
Hey Steve!

I don't feel it's prejudice. I spent quite some time trying to get it work correctly, but python packaging doesn't lend itself well to mixing libraries, executables and static assets. The effort to maintain it simply doesn't seem worth it.

**Comment by fboender** [comment]
I will accept any pull requests that implement workable Python packaging that also:

* Maintains compatibility with installs from master (make install) and installs from the tarballs / zip distribution
* Maintains compatibility with the .deb packages running on Debian 6 and 7 and Ubuntu 12.04 through 16.04 and RPM packages on Redhat 6 and 7 and CentOS 6 and 7
* Maintains compatibility with running directly from the Master branch without any installs.

Any pull requests *need* to provide proof of above situations still working in the pull request description or comments. 

Please take into consideration the following scenarios:

* No requirement to install dependencies manually, with the exception of running from Master checkout
* Compatibility with `-p local_js=1` *needs* to be maintained.

I will gladly accept pull requests that meet all the requirements mentioned above!

**Comment by fboender** [comment]
Please see issue #90 for the latest status regarding this feature request.

**Comment by fboender** [comment]
After lots of frustration with Python packaging, ansible-cmdb can now be installed using Pip!

    sudo pip install ansible-cmdb

Currently it's not possible to install ansible-cmdb in a virtualenv. Please check the manual for additional instructions.
