### ISSUE TITLE
Display inventory data in html_fancy table, even if no facts collected

### ISSUE THREAD

**Issue by keepwatch** [fboender/ansible-cmdb#86]
I have several hosts that are in inventory but have not yet been provisioned to use with Ansible, so no facts are collected for them. However, if I'm reading it correctly, [this section of code](https://github.com/fboender/ansible-cmdb/blob/master/src/ansiblecmdb/data/tpl/html_fancy.tpl#L547-L551) writes blank entries for the entire row of data (even though some inventory-collected data exists). 

I'd like some columns to be written despite there being no facts for this host. Thoughts?

**Comment by fboender** [comment]
Hey Jordan,

Did you try [https://github.com/fboender/ansible-cmdb#override--fill-in-facts](filling in facts)? I believe it should do what you want. Basically, you create a manual facts directory, and then tell ansible-cmdb to use the generated one and the manual one. 

The section below it might also be useful: [https://github.com/fboender/ansible-cmdb#manual-hosts](manual hosts)

**Comment by fboender** [comment]
I'm closing this bug report. I believe my previous comment should suffice to fix this issue. If not, please reopen the bug and we'll have a further look.
