### ISSUE TITLE
package list

### ISSUE THREAD

**Issue by asifiqbal** [fboender/ansible-cmdb#89]
This is an awesome module. How do I extend to show the list of software installed?

**Comment by fboender** [comment]
Hi!

Ansible currently doesn't gather infomation about installed software. The easiest thing to do would be to create a `/etc/ansible/facts.d` directory on each server you manage with ansible. Then you put JSON files in there with the list of installed software on that system.

Ansible-cmdb will then incoorporate those facts under the "Host local facts" section of each host.

**Comment by asifiqbal** [comment]
May be it install Puppet on remote hosts and make the puppet resource call to populate the package list? Not sure how do I feed that in your framework.

**Comment by fboender** [comment]
Yes, if Facter (https://docs.puppet.com/facter/) is installed, Ansible will automatically include its facts when gathering facts. Ansible-cmdb will show any Facter facts under the 'Facter facts" heading. If Facter includes a list of installed software, it'll show up in ansible-cmdb.
