### ISSUE TITLE
Group of groups not working

### ISSUE THREAD

**Issue by rndmh3ro** [fboender/ansible-cmdb#9]
From the Ansible docs:
>It is also possible to make groups of groups using the :children suffix. Just like above, you can apply variables using :vars:
http://docs.ansible.com/ansible/intro_inventory.html#groups-of-groups-and-group-variables

If a host belongs to a group of a group, this is currently not recognized.
You can try with this:

```
[group1]
localhost

[group_of_group:children]
group1
```

In this case, `localhost` should belong to the groups `group1` and `group_of_groups`.

**Comment by fboender** [comment]
See the discussion in issue #8 for more information.

**Comment by rndmh3ro** [comment]
It's workiung with the latest-master version!
