### ISSUE TITLE
Groups DTAP COMMENT doesn't display

### ISSUE THREAD

**Issue by ChampagneCui** [fboender/ansible-cmdb#91]
Hi,

I wrote the ansible hosts file like this:
[cust.megacorp]
1.1.1.1   dtap=dev  comment="Old database server"
1.1.1.2   dtap=dev  comment="New database server"
1.1.1.3      dtap=test 
1.1.1.4       dtap=acc  comment="24/7 support"
1.1.1.5           dtap=prod comment="Hosting by Foo" ext_id="SRV_10029"

Then:
#mkdir out
#ansible -m setup --tree out/ all
#ansible-cmdb out/ > overview.html

After I started nginx and the web appeared. Everything is OK except the 'Groups DTAP COMMENT' shows blanked.

Did I miss something?

**Comment by fboender** [comment]
Hi!

You need to supply the `-i` parameter:

`ansible-cmdb -i hosts out/ > overview.html`

Ansible-cmdb really should use it automatically if it exists in the current path / configuration, but it doesn't yet.

**Comment by fboender** [comment]
I've created issue #92 to address this.
