### ISSUE TITLE
Installation from Git does not work on OSX

### ISSUE THREAD

**Issue by Leviter** [fboender/ansible-cmdb#93]
When trying to install from Git using the commands mentioned on the repo's README, it does not work on OSX (at least on Sierra).

There is no '-r' and it fails with the error:

```
# > sudo make install
mkdir -p /usr/local/lib/ansible-cmdb
mkdir -p /usr/local/man/man1
cp -ar src/* /usr/local/lib/ansible-cmdb
cp: the -R and -r options may not be specified together.
make: *** [install] Error 1
```

**Comment by fboender** [comment]
Looks like I've been using `cp` wrong for close to 25 years. The -r option is not required when using -a. It should be fixed in the latest master.
