### ISSUE TITLE
Odd filename completion / search path when specifying template location

### ISSUE THREAD

**Issue by crisvp** [fboender/ansible-cmdb#95]
Strange things happen when specifying a template location:

```
serenity:/tmp> pwd
/tmp
serenity:/tmp> ansible-cmdb -t doesnotexist.tpl empty
Template not found: /usr/local/Cellar/ansible-cmdb/1.18/ansiblecmdb/data/tpl/doesnotexist.tpl.tpl
```
I would expect it to look in /tmp rather than /usr/local/Cellar..etc. 
The addition of the extra ".tpl" is also unexpected.

Oddly enough, this also happens when specifying the directory as a relative path:
```
serenity:/tmp> ansible-cmdb -t ./doesnotexist.tpl empty
Template not found: /usr/local/Cellar/ansible-cmdb/1.18/ansiblecmdb/data/tpl/./doesnotexist.tpl.tpl
serenity:/tmp> ansible-cmdb -t ../tmp/doesnotexist.tpl empty
Template not found: /usr/local/Cellar/ansible-cmdb/1.18/ansiblecmdb/data/tpl/../tmp/doesnotexist.tpl.tpl
```

When using an absolute path it does report the correct location, but still appends an extra ".tpl"

```
serenity:/tmp> ansible-cmdb -t /tmp/doesnotexist.tpl empty
Template not found: /tmp/doesnotexist.tpl.tpl
```

When using the same format on an existing template in the working directory it does work as expected:

```
serenity:/tmp> touch exists.tpl
serenity:/tmp> ansible-cmdb -t exists.tpl empty
serenity:/tmp>
```

As it does when specifying the absolute path:
```
serenity:/tmp> ansible-cmdb -t /tmp/exists.tpl empty
serenity:/tmp>
```

But not so much when using a relative path:
```
serenity:/tmp> ansible-cmdb -t ../tmp/exists.tpl empty
Traceback (most recent call last):
  File "/usr/local/bin/ansible-cmdb", line 128, in <module>
    mytemplate = Template(filename=options.template, default_filters=['decode.utf8'], input_encoding='utf-8', output_encoding='utf-8')
  File "/usr/local/Cellar/ansible-cmdb/1.18/mako/template.py", line 266, in __init__
    "of the root path." % self.uri)
mako.exceptions.TemplateLookupException: Template uri "../tmp/exists.tpl" is invalid - it cannot be relative outside of the root path.
```

**Comment by fboender** [comment]
Hi Cris,

These are side-effects from the templating engine used. I'll see if I can clean this up a bit, because the results you're getting are quite counter-intuitive.

**Comment by fboender** [comment]
I've pushed a commit that should make it clearer what exactly is happening when trying to find a template:

    $ pwd
    /tmp/src
    
    /tmp/src $ ./ansible-cmdb -t doesnotexist.tpl empty/
    Template 'doesnotexist.tpl' not found at any of 
      /tmp/src/doesnotexist.tpl
      /tmp/src/ansiblecmdb/data/tpl/doesnotexist.tpl.tpl
    
    /tmp/src $ ./ansible-cmdb -t ./doesnotexist.tpl empty/
    Template './doesnotexist.tpl' not found at any of 
      /tmp/src/doesnotexist.tpl
      /tmp/src/ansiblecmdb/data/tpl/doesnotexist.tpl.tpl
    
    /tmp/src $ ./ansible-cmdb -t ../src/doesnotexist.tpl empty/
    Template '../src/doesnotexist.tpl' not found at any of 
      /tmp/src/doesnotexist.tpl
      /tmp/src/ansiblecmdb/data/src/doesnotexist.tpl.tpl
    
    /tmp/src $ ./ansible-cmdb -t /tmp/src/doesnotexist.tpl empty/
    Template '/tmp/src/doesnotexist.tpl' not found at any of 
      /tmp/src/doesnotexist.tpl
      /tmp/src/doesnotexist.tpl.tpl
    
    /tmp/src $ touch exists.tpl
    /tmp/src $ ./ansible-cmdb -t ../src/exists.tpl empty/
    
    /tmp/src $ ./ansible-cmdb -t html_fancu empty/  # notice the typo
    Template 'html_fancu' not found at any of 
      /tmp/src/html_fancu
      /tmp/src/ansiblecmdb/data/tpl/html_fancu.tpl

The addition of the ".tpl" extension is still there, but that's so that users can just specify the default built-in templates by name instead of filename. Relative path names starting with ".." are now also supported.
