### ISSUE TITLE
virtualenv installation looks broken

### ISSUE THREAD

**Issue by freeseacher** [fboender/ansible-cmdb#99]
Hi! 
i've installed ansible-cmdb via pip and virtualenv.  
```
% ./bin/pip freeze
ansible==2.2.1.0
ansible-cmdb==1.19
appdirs==1.4.0
cffi==1.9.1
cryptography==1.7.2
enum34==1.1.6
idna==2.2
ipaddress==1.0.18
Jinja2==2.8.1
jsonxs==0.3
Mako==1.0.6
MarkupSafe==0.23
packaging==16.8
paramiko==2.1.1
pkg-resources==0.0.0
pyasn1==0.1.9
pycparser==2.17
pycrypto==2.6.1
pyparsing==2.1.10
PyYAML==3.12
six==1.10.0
ushlex==0.99
```
got that 
```
% ./bin/ansible-cmdb -i inv/inventory.cfg > output.html
Traceback (most recent call last):
  File "./bin/ansible-cmdb", line 45, in <module>
    tpl_dir = os.path.join(data_dir, 'tpl')
  File "/home/shirokih/projects/rt/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

**Comment by fboender** [comment]
Hi Aleksey!

Looks like you're not specifying a host facts directory. If you gathered the facts with:

    ansible -m setup --tree out/ all

You should run `ansible-cmdb` with:

    ansible-cmdb -i inv/inventory.cfg out > output.html

Ansible-cmdb should still warn about this though, so I'll make sure it issues an error when this occurs.

Thanks!

**Comment by fboender** [comment]
Sorry, the problem doesn't seem to be with incorrect invocation, but with installing into a virtualenv. I'll do some more investigation.

**Comment by freeseacher** [comment]
@fboender yep sure. of cause i test on a good command too. that was just latest command

**Comment by fboender** [comment]
This issue has been fixed in master. It will be included in the next release. I'll update this issue when the next version has arrived.
